export type LunarSourceDay = {
  lunarDay: number;
  symbol: string;
  emoji: string;
  tagline: string;
  overview: string;
  stones: string;
  meditation: string;
  relationships: string;
  activeOrgans: string[];
  doToday: string[];
  avoidToday: string[];
  foodNote: string;
  dreamFocus: string;
  dreamGuidance: string;
  sourceUrl: string;
};

export const lunarDaySource: LunarSourceDay[] = [
  {
    lunarDay: 1,
    symbol: "Candle",
    emoji: "🕯️",
    tagline: "This is a day of creative projects planning.",
    overview: "It is not recommended to start new projects; current affairs would be better postponed. Things planned on this day should be successfully accomplished.",
    stones: "Diamond, rock crystal.",
    meditation: "Candle and fire purification — concentrate on an open flame for 10-15 minutes to release fears and obsessions before planning the month ahead.",
    relationships: "During the new moon it is not favorable to visit the Civil Registry Office or hold a wedding feast; it is better to stay in a peaceful place and think things over. It is, however, the best time for planning a wedding ceremony.",
    activeOrgans: ["Head", "Brain", "Eyes", "Sinuses"],
    doToday: ["Set monthly intentions", "Candle meditation", "Light planning"],
    avoidToday: ["Heavy decisions", "Financial transactions", "Physical strain"],
    foodNote: "Light vegetarian foods only. Avoid spicy, fatty, or stimulating foods, alcohol, coffee, and tea.",
    dreamFocus: "Month-ahead sketches",
    dreamGuidance: "Dreams can sketch the coming lunar month. Notice desires, plans, and constructive images; include the useful ones in your new-moon intentions.",
    sourceUrl: "https://om-journal.com/moonday/1"
  },
  {
    lunarDay: 2,
    symbol: "Horn of plenty",
    emoji: "🌾",
    tagline: "One can knows what things are necessary by feeling, when eating and contacting with people.",
    overview: "This day is favorable for starting cycles of physical exercises or large educational cycles. Eat only the food you like, and follow this same principle in your contacts with people.",
    stones: "Jadeite, chalcedony, agate.",
    meditation: "Body-awareness meditation — place your hands on the belly and sense which foods, people, or plans truly agree with you.",
    relationships: "This day is one of the best for marriage; families formed this day are usually solid and friendly. It is favorable to show concern for relatives, have dates, and give a present to your beloved partner.",
    activeOrgans: ["Mouth", "Throat", "Gums", "Neck"],
    doToday: ["Speak your desires aloud", "Begin new projects", "Connect with abundance"],
    avoidToday: ["Negative speech", "Fasting", "Disputes"],
    foodNote: "Nourishing, generous meals. Dairy and grains support today's energy. Avoid going hungry.",
    dreamFocus: "Karmic blueprint",
    dreamGuidance: "Dreams may point toward recurring life tasks or karmic knots. Treat difficult images calmly; they can show what wants attention this month.",
    sourceUrl: "https://om-journal.com/moonday/2"
  },
  {
    lunarDay: 3,
    symbol: "Leopard",
    emoji: "🐆",
    tagline: "This is a day of fighting man, of feat.",
    overview: "This is a very energetic day. It is time to act; being passive is not recommended, and it is a favorable day for intense physical exercise.",
    stones: "Ruby, pyrite, aventurine.",
    meditation: "Martial arts and body relaxation — release tension and old anger by breathing through each part of the body in turn.",
    relationships: "The 3rd lunar day is unfavorable for marriage, but if you decide to hold a wedding ceremony this day, perform it in an extraordinary way. Avoid harsh words and remember that partners need tenderness, not displeasure.",
    activeOrgans: ["Shoulders", "Arms", "Hands", "Joints"],
    doToday: ["Physical activity", "Assert boundaries", "Show courage"],
    avoidToday: ["Passive waiting", "Starting new relationships", "Excess indulgence"],
    foodNote: "Energizing foods. Keep portions moderate; avoid overeating or heavy meals.",
    dreamFocus: "Energy and courage",
    dreamGuidance: "Dreams can reveal how your energy is moving. Struggle, resistance, or victory imagery is useful for reading your inner strength.",
    sourceUrl: "https://om-journal.com/moonday/3"
  },
  {
    lunarDay: 4,
    symbol: "Tree of Knowledge",
    emoji: "🌳",
    tagline: "This is a day of choice between good or evil, in actions and in thoughts.",
    overview: "Solitude is advisable. Gardening, housekeeping, walking, relaxing, and communicating with nature are recommended, while group work and hasty decisions are not.",
    stones: "Sardonyx, amazon stone, green nephrite.",
    meditation: "Mantra chanting and time in nature — walking outdoors or singing 'AUM' helps ground the day's uncertain energy.",
    relationships: "Do not plan a wedding ceremony this day, and consider canceling romantic dates if you expect important results. Careless or offensive words come easily now, so choose them with care.",
    activeOrgans: ["Stomach", "Digestive system", "Chest"],
    doToday: ["Seek wisdom", "Quiet reflection", "Careful planning"],
    avoidToday: ["Rash decisions", "Arguments", "Starting major new ventures"],
    foodNote: "Simple, clean foods. Avoid excess; this day calls for restraint and clarity.",
    dreamFocus: "Warnings and inherited patterns",
    dreamGuidance: "Dreams may come true, especially vivid ones. Tangled images ask you to revise plans; relatives can point to inherited patterns ready for care.",
    sourceUrl: "https://om-journal.com/moonday/4"
  },
  {
    lunarDay: 5,
    symbol: "Unicorn",
    emoji: "🦄",
    tagline: "Keep your inner rod, accomplish alchemy of soul and meal.",
    overview: "Everything will be successful, if you are creative and concentrate on your aim. You should be true to your principles, feelings and emotions.",
    stones: "Turquoise, pink chalcedony, marble.",
    meditation: "Meditation while eating — mindful, slow consumption.",
    relationships: "It's time for changes, unexpected discoveries and revelation. It is not favorable to constitute a family mostly for couples who doesn't live together enough.",
    activeOrgans: ["Esophagus", "Chest", "Third eye (Ajna)"],
    doToday: ["Finish started projects", "Pay debts", "Cook mindfully"],
    avoidToday: ["Fasting", "Losing valuables", "New financial ventures"],
    foodNote: "Dairy, fruits, honey. Avoid meat, nuts, fermented foods, grains, seeds, and alcohol. Do not overeat.",
    dreamFocus: "Health and movement",
    dreamGuidance: "Good dreams are promising, while disturbing ones ask for health and energy care. Roads, movement, and even crying can be positive signs.",
    sourceUrl: "https://om-journal.com/moonday/5"
  },
  {
    lunarDay: 6,
    symbol: "Crane",
    emoji: "🦢",
    tagline: "Breathing and sound could heal any illness.",
    overview: "This is a day of solitude and humbleness. Intuition is heightened, and any breathing exercises, including aromatherapy, are useful.",
    stones: "Hyacinth, citrine.",
    meditation: "Breathing and sound therapy — tune into the sounds of nature, wind, birdsong, or rain, as a form of meditation.",
    relationships: "This day can bring peace and regularity to a new family; couples formed today tend to achieve wisdom and keep love for the long term. Venus is influential, making it a good day for dates.",
    activeOrgans: ["Large intestine", "Abdomen", "Lower digestive tract"],
    doToday: ["Ask clear questions before sleep", "Intuitive self-care", "Gentle exercise"],
    avoidToday: ["Sharing dream content widely", "Anger or conflict", "Overexertion"],
    foodNote: "Light, cleansing foods. A gentle day for dietary adjustments and digestive care.",
    dreamFocus: "Private revelation",
    dreamGuidance: "Dreams can carry answers, but are best kept private. Ask a clear question before sleep and write down the images immediately on waking.",
    sourceUrl: "https://om-journal.com/moonday/6"
  },
  {
    lunarDay: 7,
    symbol: "Wind rose",
    emoji: "🧭",
    tagline: "Do not tell undue, watch over words' purity.",
    overview: "Words possess a particular power today, and what you say might easily come true. One should not lie or chatter to no purpose; it is better to keep silent.",
    stones: "Sapphire, heliotrope, coral.",
    meditation: "Mindful speech and affirmation — speak sparingly, and when you do, choose your words, prayers, or mantras with care, since they carry unusual power today.",
    relationships: "For creative persons this day is ideal for starting a family, with rigorous companionship as the basis of the relationship. Anything said today can become real, so let loving words be the topic of conversation.",
    activeOrgans: ["Throat", "Thyroid", "Vocal cords", "Neck"],
    doToday: ["Express your purpose", "Travel or plan journeys", "Speak your truth"],
    avoidToday: ["Idle talk", "Harsh or careless words", "Overcommitting"],
    foodNote: "Varied, moderate meals. Warm liquids and herbal teas support the throat.",
    dreamFocus: "Words and purpose",
    dreamGuidance: "Pay special attention to spoken words in dreams. They may carry useful guidance about your direction, though fulfillment may take time.",
    sourceUrl: "https://om-journal.com/moonday/7"
  },
  {
    lunarDay: 8,
    symbol: "Phoenix",
    emoji: "🔥",
    tagline: "This is a day of repentance, clearance and transformation.",
    overview: "This is an active day, and unforeseen events are possible. It is a good day to think over your life; bathing, laundry, and alcohol are not recommended.",
    stones: "Red granite, chrysolite, morion.",
    meditation: "Fire purification — sit by a flame to release negative emotions, then cleanse your home by candlelight.",
    relationships: "Try to avoid starting a family this day, though unions begun now can suit active, well-traveled couples. People tend to be open-hearted, so avoid sarcasm and malice.",
    activeOrgans: ["Heart", "Chest", "Upper back", "Spine"],
    doToday: ["Release old patterns", "Creative reinvention", "Transformation practices"],
    avoidToday: ["Clinging to the past", "Emotional extremes", "Reckless action"],
    foodNote: "Warming, heart-nourishing foods. Avoid stimulants and alcohol.",
    dreamFocus: "Transformation",
    dreamGuidance: "Dreams may show unrealized gifts, old unfinished problems, or your readiness for change. Open spaces suggest movement; dead ends ask for renewal.",
    sourceUrl: "https://om-journal.com/moonday/8"
  },
  {
    lunarDay: 9,
    symbol: "Bat",
    emoji: "🦇",
    tagline: "Be on the watch, discern between situations when evil forces seduce and when the light of truth shines.",
    overview: "Over these 24 hours negative emanations have influence on humans. This is a day of provocations; beware of trickery, temptation, seduction and illusion.",
    stones: "Black pearl, alexandrite, smoky topaz, ophite.",
    meditation: "White-light protection — this complicated day favors simple visualization of white light over deep meditation, with incense or bells to clear the home.",
    relationships: "This day is the most unfavorable for wedding ceremonies, and conflicts between partners are common. Try to cancel a first rendezvous and keep negative emotions in check.",
    activeOrgans: ["Kidneys", "Lower back", "Adrenal glands"],
    doToday: ["Face hidden truths", "Inner reflection", "Rest and recover"],
    avoidToday: ["Major decisions", "New beginnings", "Provocative situations"],
    foodNote: "Kidney-supportive foods: water-rich vegetables, barley, warm soups. Avoid salt and alcohol.",
    dreamFocus: "Hidden conflict",
    dreamGuidance: "Dreams may be intense or unpleasant because hidden conflicts are surfacing. Extract the lesson, then let the heavy images go.",
    sourceUrl: "https://om-journal.com/moonday/9"
  },
  {
    lunarDay: 10,
    symbol: "Fountain",
    emoji: "⛲",
    tagline: "Strengthen your home, do not forget your background.",
    overview: "One must direct one's steps towards strengthening family relations. It is recommended to support family traditions, and fundamental initiatives such as house building or repair are favored.",
    stones: "Amber, sardonyx.",
    meditation: "Ancestor and family-line meditation — connect with your lineage, ask for their wisdom, or share a meal with relatives.",
    relationships: "The 10th lunar day is the most favorable for starting a family and holding a wedding ceremony; couples formed this day tend toward stable relations filled with love and respect. It is also a good day to meet a partner's family.",
    activeOrgans: ["Joints", "Connective tissue", "Back", "Spine"],
    doToday: ["Honor family and ancestors", "Acts of gratitude", "Generous giving"],
    avoidToday: ["Selfishness", "Waste", "Breaking important traditions"],
    foodNote: "Nourishing, traditional foods. Generous meals are favorable; share food with others.",
    dreamFocus: "Family line",
    dreamGuidance: "Dreams can carry family, ancestry, or lineage themes. Bright dreams may be light and symbolic; disturbing dreams should be acknowledged and released.",
    sourceUrl: "https://om-journal.com/moonday/10"
  },
  {
    lunarDay: 11,
    symbol: "Kundalini",
    emoji: "🐍",
    tagline: "Awakening of primary energy, named kundalini. This is a day of ekadashi.",
    overview: "This is the most energetic day. Today it is necessary to use caution and attentiveness in every task, and whatever is started today should be brought to a close.",
    stones: "Fire opal, hematite, carnelian.",
    meditation: "Kundalini and inner-fire meditation — favors fasting, solitude, and working through the chakras to awaken latent energy.",
    relationships: "This lunar day is favorable for starting a family, though the energy is very high and overuse of alcohol should be avoided at any wedding festival. Take care of your partner and offer a gift rather than dwelling on future plans.",
    activeOrgans: ["Legs", "Calves", "Circulation", "Subtle energy channels"],
    doToday: ["Meditation and energy practices", "Creative or spiritual work", "Yoga or movement"],
    avoidToday: ["Excesses of any kind", "Impulsive spending", "Draining energy through conflict"],
    foodNote: "Light, sattvic foods. Avoid meat and stimulants. Fasting is supported if feeling called.",
    dreamFocus: "Material and spiritual balance",
    dreamGuidance: "Dreams can show whether your material life and spiritual life are moving together. Your role in the dream is the main clue.",
    sourceUrl: "https://om-journal.com/moonday/11"
  },
  {
    lunarDay: 12,
    symbol: "Heart",
    emoji: "❤️",
    tagline: "Love can open heart.",
    overview: "Feelings of love, compassion and charity are especially active today. It is favorable to pray and clear your thoughts, and this is an ideal day for marriage.",
    stones: "Lazurite, yellow coral, mother-of-pearl, pink pearl.",
    meditation: "Water and heart meditation — sit near flowing water, or the sound of it, and let your emotions settle into peace.",
    relationships: "This is one of the best days to start a family for partners of any age; couples formed on the 12th lunar day are usually fortunate and seldom end in divorce. Take maximum care of your partner and avoid causing offense.",
    activeOrgans: ["Heart", "Cardiovascular system", "Chest", "Blood"],
    doToday: ["Acts of love and compassion", "Heart-centered reflection", "Giving and receiving"],
    avoidToday: ["Conflict and cruelty", "Overwork", "Emotional suppression"],
    foodNote: "Heart-nourishing foods: berries, leafy greens, dark chocolate. Avoid excess saturated fats.",
    dreamFocus: "Values",
    dreamGuidance: "Dreams can reveal whether material or spiritual values are dominating. Bright, well-remembered dreams deserve attention.",
    sourceUrl: "https://om-journal.com/moonday/12"
  },
  {
    lunarDay: 13,
    symbol: "Wheel",
    emoji: "☸️",
    tagline: "Wheel rotates, movement continues.",
    overview: "This is a good day for group work, acquiring new information and initiating new training cycles. Use today for accumulation and making household items; baking bread is suggested.",
    stones: "Noble opal.",
    meditation: "Renewal Wheel meditation — visualize breaking a repeating pattern in your life to release old mental blockages.",
    relationships: "This is a favorable day to start a family among scientists, travelers, geologists, and researchers. Couples formed this lunar day are usually provident, disciplined, and well planned.",
    activeOrgans: ["Reproductive system", "Pelvis", "Lower abdomen"],
    doToday: ["Break old cycles", "Review recurring patterns", "Seek conscious change"],
    avoidToday: ["Repeating past mistakes", "Leaving things half-finished", "Complacency"],
    foodNote: "Light, cleansing meals. Avoid excess. Fresh vegetables and juices support the cycle-breaking energy.",
    dreamFocus: "Breaking loops",
    dreamGuidance: "Dreams may show where you are repeating a loop and where change is possible. Record them quickly; warnings may unfold soon.",
    sourceUrl: "https://om-journal.com/moonday/13"
  },
  {
    lunarDay: 14,
    symbol: "Two pipes",
    emoji: "🎵",
    tagline: "Trumpet calls to start matters of great importance.",
    overview: "This day brings fortune for new beginnings, and projects started today will tend to succeed on their own merit. There is a strong connection to information and study today.",
    stones: "Hyacinth.",
    meditation: "Sacred sound meditation — chant 'OM' or 'AUM' and consider starting a new mantra cycle or 40-day practice.",
    relationships: "This is a favorable day to start a family for partners with a long premarital relationship, and also a good time for divorced persons to begin again. During a date people are often shy, so listen carefully for what is left unsaid.",
    activeOrgans: ["Feet", "Lymphatic system", "Lower body", "Immune system"],
    doToday: ["Music and creative arts", "Develop latent gifts", "Gentle spiritual practices"],
    avoidToday: ["Overexertion", "Confrontations", "Excess food or drink"],
    foodNote: "Moderate, balanced diet. Hydration is especially important today.",
    dreamFocus: "Hidden abilities",
    dreamGuidance: "Dreams are usually not predictive today, but they may reveal abilities that deserve development. Heavy dreams can be released lightly.",
    sourceUrl: "https://om-journal.com/moonday/14"
  },
  {
    lunarDay: 15,
    symbol: "Fiery serpent",
    emoji: "🐉",
    tagline: "Ascesis, self-discipline.",
    overview: "Today is a full moon and a high-energy day. There is a large chance of giving way to temptation or laziness, so it is advisable to control your passions and strengthen self-discipline.",
    stones: "Agate, morion, jet.",
    meditation: "Silent meditation — sit quietly at peak moonlight and let thoughts pass like clouds without disturbing your calm.",
    relationships: "This is a very complicated lunar day; only mature and experienced partners have a good chance of starting a family. Young couples not yet ready may face disappointment, and this is an unfavorable day for a rendezvous.",
    activeOrgans: ["Liver", "Gallbladder", "Whole body at peak energy"],
    doToday: ["Celebrate and express yourself", "Reflect on the cycle so far", "Full-moon ritual"],
    avoidToday: ["Alcohol", "Overeating", "Heated arguments"],
    foodNote: "Liver-supportive foods: beets, bitter greens, artichoke. Avoid alcohol and heavy fats absolutely.",
    dreamFocus: "Subconscious weather",
    dreamGuidance: "Dreams mirror your current inner state. Bright dreams may be prophetic if kept private; heavy dreams point to imbalance and the next cycle's work.",
    sourceUrl: "https://om-journal.com/moonday/15"
  },
  {
    lunarDay: 16,
    symbol: "Butterfly",
    emoji: "🦋",
    tagline: "Harmony and balance of mind and body.",
    overview: "Keep your balance; exercises favoring equilibrium are advisable today. This is a good day for cleaning, tidying up, and taking a ritualistic bath.",
    stones: "Spinel, tourmaline, charoite, emerald, pearl (except black).",
    meditation: "Moonlight meditation — visualize soft white light filling and calming the body, restoring balance and beauty.",
    relationships: "It is not recommended to start a family or perform a marriage ceremony this day, though it is favorable to begin a honeymoon or make an offer of marriage. Romantic rendezvous go well in a calm, peaceful place.",
    activeOrgans: ["Kidneys", "Skin", "Lower back", "Lymph"],
    doToday: ["Beauty rituals", "Artistic expression", "Release and let go"],
    avoidToday: ["Harsh words", "Decisions made in strong emotion", "Overindulgence"],
    foodNote: "Light and cleansing. Kidney-supportive choices: cucumber, watermelon, lemon water.",
    dreamFocus: "Cleansing and balance",
    dreamGuidance: "Dreams help release tension and restore balance. Nightmares can be read as the psyche clearing old pressure rather than as bad omens.",
    sourceUrl: "https://om-journal.com/moonday/16"
  },
  {
    lunarDay: 17,
    symbol: "Shakti",
    emoji: "⚡",
    tagline: "Love and festivity are triumphing.",
    overview: "This is a day of flowering female energy, joy and inner liberty. Today is favorable for love, marital relations, or pairing up in general.",
    stones: "Transparent amethyst, raven's eye, hawk's-eye, zircon.",
    meditation: "Laughter and dance meditation — begin the day by laughing before opening your eyes, then let joyful movement carry through the day.",
    relationships: "This day is favorable for wedding festivals and jubilees, ideally followed by a honeymoon trip right after the celebration. Female energy is high, making dancing, intimacy, and connection with a partner especially favorable.",
    activeOrgans: ["Reproductive organs", "Sacral center", "Endocrine system"],
    doToday: ["Creative projects", "Expressive movement or dance", "Cultivate vitality"],
    avoidToday: ["Suppressing creative energy", "Depressive thoughts", "Excessive restriction"],
    foodNote: "Energizing, warming foods. Ginger, cinnamon, and natural spices are beneficial.",
    dreamFocus: "Creative life force",
    dreamGuidance: "Dreams reflect sexual and creative energy. Pleasant dreams suggest flow; unpleasant ones ask where vitality has been suppressed.",
    sourceUrl: "https://om-journal.com/moonday/17"
  },
  {
    lunarDay: 18,
    symbol: "Mirror",
    emoji: "🪞",
    tagline: "The outer reflects the inner.",
    overview: "Everything that happens to us today is a reflection of our true self. It is useful to look inside yourself and find the reasons behind your actions and opinions.",
    stones: "White agate, opal, lilac amethyst, spinel.",
    meditation: "Mirror meditation — reflect on the people around you as mirrors of yourself, then visualize your ideal self filled with light.",
    relationships: "It is best to abstain from starting a family or holding a marriage ceremony this day. Consider canceling a romantic rendezvous, or be ready to hear something revealing about yourself from your partner.",
    activeOrgans: ["Stomach", "Intestines", "Digestive fire"],
    doToday: ["Self-reflection and journaling", "Honest inner review", "Sit with what you see"],
    avoidToday: ["Vanity or self-deception", "Excessive screen time", "Ignoring difficult truths"],
    foodNote: "Easily digestible foods. Avoid overeating; probiotic foods like yogurt support digestive clarity.",
    dreamFocus: "Self-reflection",
    dreamGuidance: "Dreams mirror the gap between who you are living as and who you want to become. They may also show blocks, health hints, or practical openings.",
    sourceUrl: "https://om-journal.com/moonday/18"
  },
  {
    lunarDay: 19,
    symbol: "Spider",
    emoji: "🕷️",
    tagline: "Cleaning of soul and conscience. Someone else's thoughts must go away.",
    overview: "The Spider is weaving its net; be cautious with new ideas today. One must not pay debts, borrow, or enter into contracts, and cleansing fire rituals are advisable.",
    stones: "Labradorite, morion, bloodstone, chrysolite, green granite.",
    meditation: "Purification meditation — cleanse your living space and body with water, incense, or a candle, using an affirmation of release.",
    relationships: "It is not favorable to start a family or perform a marriage ceremony this day, nor is it a good day for divorce. It is an unfavorable time for a romantic rendezvous, with a high chance of a serious falling out.",
    activeOrgans: ["Lymphatic system", "Spleen", "Blood", "Immune system"],
    doToday: ["Gentle spiritual practice", "Prayer or ritual", "Ask for outside support"],
    avoidToday: ["Complex decisions", "Starting new projects", "Travel or major moves"],
    foodNote: "Simple, cleansing foods. Very light meals or fasting is beneficial. Avoid heavy or processed foods.",
    dreamFocus: "Deep psyche",
    dreamGuidance: "Dreams may be difficult and should not be interpreted too literally. Use prayer, release, or outside support if the imagery feels heavy.",
    sourceUrl: "https://om-journal.com/moonday/19"
  },
  {
    lunarDay: 20,
    symbol: "Eagle",
    emoji: "🦅",
    tagline: "Reject all doubts, adopt your transformation.",
    overview: "This is a day of revelations, disclosures, spiritual transformation and overcoming doubt. Inner transformation is possible today, and it favors releasing debts and poor conditions.",
    stones: "Red jasper, jasperite.",
    meditation: "Meeting the Inner Teacher — a guided visualization of rising above the earth to receive wisdom from your higher self.",
    relationships: "This is a favorable day for a wedding celebration; families formed on the 20th lunar day are seldom disrupted by jealousy, betrayal, or financial problems. It is a good day for a calm, peaceful romantic date.",
    activeOrgans: ["Eyes", "Liver", "Vision centers", "Brain"],
    doToday: ["Intentional dreaming", "Set clear goals", "Strategic planning"],
    avoidToday: ["Scattered attention", "Avoiding truth", "Procrastinating on important matters"],
    foodNote: "Liver-supportive foods: artichoke, dandelion greens, fresh vegetable juices. Avoid alcohol.",
    dreamFocus: "Requested answers",
    dreamGuidance: "Dreams can come true quickly and may be intentionally requested. Ask for a solution, a place, or a subtle-world journey before sleep.",
    sourceUrl: "https://om-journal.com/moonday/20"
  },
  {
    lunarDay: 21,
    symbol: "Herd of horses",
    emoji: "🐎",
    tagline: "This is a day of justice, of people consolidation and forward motion.",
    overview: "This is a day of courage and steadfast advancement, with active and creative energy prevalent. It is a good day for group activity, conclusions, or heading off on a trip.",
    stones: "Pyrite, zircon, aventurine, obsidian.",
    meditation: "Pranayama and breathwork — favors rebirthing sessions and vigorous breathing practices alongside physical movement.",
    relationships: "The 21st lunar day is favorable for a wedding celebration, which should be merry and large-scale. It is a good day for a romantic date, and avoiding loneliness helps ward off low spirits.",
    activeOrgans: ["Hips", "Thighs", "Liver", "Musculoskeletal system"],
    doToday: ["Physical movement and exercise", "Express creative power", "Make bold moves"],
    avoidToday: ["Stagnation", "Holding back ideas", "Passive waiting"],
    foodNote: "Energizing, protein-rich foods. Physical vitality is the theme; eat to fuel movement.",
    dreamFocus: "Creative power",
    dreamGuidance: "Dreams mainly show whether creative energy is present or blocked. Beyond that, they are usually less important and rarely predictive.",
    sourceUrl: "https://om-journal.com/moonday/21"
  },
  {
    lunarDay: 22,
    symbol: "Ganesha",
    emoji: "🐘",
    tagline: "This is a day of wisdom and knowledge.",
    overview: "Learning, researching, or any work with information is favorable today. If dedicated to studies, this day can bring progress comparable to years of hard work.",
    stones: "Blue agate, blue sapphire, blue jasper, blue nephrite, amber.",
    meditation: "Concentration practice — focus deeply on a subject, symbol, or text you wish to understand more fully.",
    relationships: "It is not favorable to start a family this day, though it is an excellent time to celebrate a silver or golden wedding anniversary. Each meeting today can reveal something new and meaningful about love or a partner.",
    activeOrgans: ["Liver", "Large intestine", "Detox pathways"],
    doToday: ["Study and learning", "Ritual or ceremony beginnings", "Problem-solving"],
    avoidToday: ["Laziness", "Skipping established practices", "Procrastination"],
    foodNote: "Cleansing foods: vegetables, grains, legumes. A gentle detox is supported today.",
    dreamFocus: "Knowledge",
    dreamGuidance: "Dreams may be empty, or they may bring knowledge and problem-solving. Ask a question before bed and write down what arrives.",
    sourceUrl: "https://om-journal.com/moonday/22"
  },
  {
    lunarDay: 23,
    symbol: "Crocodile",
    emoji: "🐊",
    tagline: "This is a day of provocation and temptations.",
    overview: "This is a day of repentance, forgiveness and fasting. House cleaning, tidying up, and piety are recommended, and it is best to avoid contacts.",
    stones: "Smoky topaz, black nephrite.",
    meditation: "Home purification meditation — cleanse your space with incense or holy water while visualizing sunlight filling the room.",
    relationships: "The 23rd lunar day is unfavorable for starting a family, and divorces proceed quickly and painlessly now. If a relationship is strained, avoid contact and control negative reactions rather than trying to make peace today.",
    activeOrgans: ["Kidneys", "Urethra", "Water metabolism"],
    doToday: ["Adapt and reconsider", "Question assumptions", "Review plans with fresh eyes"],
    avoidToday: ["Taking things at face value", "Impulsive conclusions", "Risky ventures"],
    foodNote: "Hydrating, kidney-supportive foods. Reduce salt and processed foods today.",
    dreamFocus: "Contradiction",
    dreamGuidance: "Dreams can be deceptive or reversed today. Treat strong conclusions carefully; the opposite meaning may be closer to the truth.",
    sourceUrl: "https://om-journal.com/moonday/23"
  },
  {
    lunarDay: 24,
    symbol: "Shiva",
    emoji: "🙏",
    tagline: "One creates the new after having destroyed the old.",
    overview: "This is a day of masculine energy revival. The power of nature is at its most active today, and physical strength intensively increases.",
    stones: "Black jasper, air obsidian, malachite, blue nephrite, grossular garnet.",
    meditation: "Tantra and earth-connection practices — work with minerals, yoga, or nature to ground masculine, generative energy.",
    relationships: "This is the best day to start a family for couples planning to have many children. Masculine energy and sexual potential are strong, making a romantic rendezvous especially effective.",
    activeOrgans: ["Heart", "Reproductive center", "Vital energy (prana)"],
    doToday: ["Devotional or spiritual practice", "Deep creative work", "Transformation rituals"],
    avoidToday: ["Wasting vital energy", "Trivial distractions", "Ego-driven actions"],
    foodNote: "Sattvic, pure foods. Avoid all intoxicants. This is a sacred day for conscious nourishment.",
    dreamFocus: "Inner strength",
    dreamGuidance: "Dreams show creative force, sexual energy, and overall potential. Good dreams suggest strength; difficult ones reveal where energy leaks.",
    sourceUrl: "https://om-journal.com/moonday/24"
  },
  {
    lunarDay: 25,
    symbol: "Turtle",
    emoji: "🐢",
    tagline: "Lend ear in silence to the voice of your soul.",
    overview: "This is a passive and meditative day, a period of hypersensitivity, concentration and imagination. You should lend an attentive ear to your inner voice, and there is no need to hurry.",
    stones: "Spar, tiger's-eye, hawk's-eye, cat's-eye, pink marble.",
    meditation: "Guardian-angel meditation — before sleep, invite a dialogue with your guardian angel or higher powers to help clarify your life's mission.",
    relationships: "It is better to avoid starting a family this day, though divorce proceedings go quickly and painlessly. A romantic rendezvous will go well, if without much lift in feeling; this is a day better spent in solitude, reflecting on your relationships.",
    activeOrgans: ["Nervous system", "Brain", "Sensory organs"],
    doToday: ["Slow, contemplative work", "Nature walks and quiet time", "Intuitive reading or divination"],
    avoidToday: ["Rushing", "Overstimulation", "Harsh or noisy environments"],
    foodNote: "Nourishing, nerve-calming foods. Warm soups, herbal teas, and gentle proteins are supportive.",
    dreamFocus: "Intuitive prophecy",
    dreamGuidance: "Dreams are traditionally treated as prophetic today, but intuition matters more than literal analysis. Cleanse and release nightmares in the morning.",
    sourceUrl: "https://om-journal.com/moonday/25"
  },
  {
    lunarDay: 26,
    symbol: "Swamp",
    emoji: "🌿",
    tagline: "No wisdom like silence. This is a day of ekadashi (the 11th day after fullmoon).",
    overview: "Wasted efforts are possible today, and idle talk is a waste of energy. Abstain from intensive activity; it is better to relax and be selective with your contacts.",
    stones: "Yellow nephrite, jadeite, chrysoprase.",
    meditation: "Silent observation — practice vipassana or simple breath-watching in solitude, a fitting day to contact your Inner Teacher.",
    relationships: "This is an unfavorable day to start a family, and it is a suitable time for divorce if needed. Avoid contact with new people, but continue to support and help a partner in an already stable relationship.",
    activeOrgans: ["Reproductive system", "Spinal fluid", "Immune system"],
    doToday: ["Honest self-reflection", "Clearing bad habits", "Grounding in nature"],
    avoidToday: ["Pride or self-deception", "Toxic environments", "Gossip and vanity"],
    foodNote: "Grounding, cleansing foods. Avoid fermented or intoxicating foods today.",
    dreamFocus: "Habits and pride",
    dreamGuidance: "Dreams can reveal habits, vices, pride, or self-esteem distortions. Colorful dreams may lift the mood and can come true.",
    sourceUrl: "https://om-journal.com/moonday/26"
  },
  {
    lunarDay: 27,
    symbol: "Trident",
    emoji: "🔱",
    tagline: "Sober mind and spirit open the way to concealed knowledge.",
    overview: "The challenge placed before people today is to find themselves and share what they discover with others. This is a fine day for meditation, with intuitive insight and concealed knowledge available.",
    stones: "Lilac amethyst, emerald, adularia, pink and crimson quartz, selenite.",
    meditation: "Sacred music and prayer — chant mantras or pray for others to open an intuitive channel of insight today.",
    relationships: "Today is a good time to start a family, though for stability the wedding ceremony should be quiet and calm, with sea or ship motifs in the decor. It is a favorable day for romantic meetings and for making peace after conflict.",
    activeOrgans: ["Shins", "Ankles", "Endocrine system"],
    doToday: ["Meditation and spiritual study", "Develop intuition", "Sober inner work"],
    avoidToday: ["Alcohol and intoxicants", "Excess or indulgence", "Shallow or distracting pursuits"],
    foodNote: "Spiced, warming meals. Cardamom, turmeric, clove, and pepper are favorable. Avoid potatoes, citrus, and alcohol.",
    dreamFocus: "True nature",
    dreamGuidance: "Dreams and omens can carry intuitive knowledge and reveal the true nature of people or situations. Interpret gently; mistakes are easy today.",
    sourceUrl: "https://om-journal.com/moonday/27"
  },
  {
    lunarDay: 28,
    symbol: "Lotus",
    emoji: "🪷",
    tagline: "Quiet and favorable day.",
    overview: "Today should be lived actively and in good humor. One may start new projects, and the day is particularly favorable for the purchase of land or real estate.",
    stones: "Chrysoprase, milk opal, jade, aquamarine, amethyst.",
    meditation: "Chakra and lucid-dream meditation — favorable for clearing the chakras and practicing dream awareness, such as looking at your hands before sleep.",
    relationships: "On this day it is favorable to start a family for older, experienced partners. It is a suitable day for calm meetings where you have a chance to discover new feelings and character in each other.",
    activeOrgans: ["Blood", "Cardiovascular system", "Heart center"],
    doToday: ["Love rituals and heart opening", "Service to others", "Expressing gratitude"],
    avoidToday: ["Bitterness or resentment", "Blocking emotional flow", "Isolation"],
    foodNote: "Heart-nourishing, gentle foods. Hydration is especially important. Eat with love and attention.",
    dreamFocus: "Obstacles and love",
    dreamGuidance: "Dreams may show obstacles, solutions, future hints, and the emotional field of love. Treat them as notices shaped by your choices.",
    sourceUrl: "https://om-journal.com/moonday/28"
  },
  {
    lunarDay: 29,
    symbol: "Hydra",
    emoji: "🌊",
    tagline: "Clean yourself and your house, and keep clean.",
    overview: "Stay abstinent and humble, and practice humility and repentance; today is a good day for fasting and healing. Do not start anything new, but follow through on what you already began.",
    stones: "Black pearl, mother-of-pearl, obsidian, white opal, labradorite, colored jasper.",
    meditation: "Purification meditation — a brief cold foot bath, or a candle burned all the way down, helps release negative energy.",
    relationships: "On this day it is recommended to abstain from starting a family or holding a wedding celebration. It is also an unfavorable day for divorce, given the high possibility of quarrels and scandal.",
    activeOrgans: ["Kidneys", "Urinary tract", "Detox pathways"],
    doToday: ["Clear and release old energy", "Finish outstanding business", "Prayer and forgiveness"],
    avoidToday: ["Starting new projects", "Conflict or confrontation", "Draining environments"],
    foodNote: "Very light, cleansing diet. Fasting or minimal eating supports the clearing energy of this day.",
    dreamFocus: "Difficult clearing",
    dreamGuidance: "Dreams may be complicated or frightening because subconscious negativity is clearing. Keep the day harmonious and seek support for heavy material.",
    sourceUrl: "https://om-journal.com/moonday/29"
  },
  {
    lunarDay: 30,
    symbol: "Golden Swan",
    emoji: "🕊️",
    tagline: "Sum up, adopt yourself and make a step to the new day.",
    overview: "This is an especially harmonious and easy day, one that should be dedicated to completing affairs or a monthly summing up. One should pay debts and let go of anything superfluous.",
    stones: "Madrepore, rock crystal, tourmaline.",
    meditation: "Reflective nature meditation — sit outdoors and review the past month, affirming what to keep and what to release.",
    relationships: "On this day it is recommended to abstain from starting a family, as unions formed now can be short-term and weak. It is best spent with a beloved partner in a quiet, peaceful place, outdoors if possible.",
    activeOrgans: ["Spine", "Nervous system", "Whole body integration"],
    doToday: ["Gratitude and completion rituals", "Review and honor the lunar month", "Rest and integrate"],
    avoidToday: ["Starting new ventures", "Overexertion", "Careless or rushed actions"],
    foodNote: "Celebratory yet balanced meals. Honor the cycle with conscious, grateful eating.",
    dreamFocus: "Cycle completion",
    dreamGuidance: "Dreams may be bright and meaningful, especially if you have worked with the month consciously. Record what closes and what asks for attention next.",
    sourceUrl: "https://om-journal.com/moonday/30"
  }
];

export function getLunarSourceDay(lunarDay: number) {
  return lunarDaySource[(lunarDay - 1 + lunarDaySource.length) % lunarDaySource.length];
}
