import type { LunarSourceDay } from "./lunarDaySource";

export const lunarDaySourceDe: LunarSourceDay[] = [
  {
    lunarDay: 1,
    symbol: "Kerze",
    emoji: "🕯️",
    tagline: "Ein Tag, um kreative Vorhaben zu planen.",
    overview: "Heute ist kein guter Zeitpunkt, um Neues zu starten; laufende Angelegenheiten schiebst du besser auf. Was du an diesem Tag planst, hat gute Chancen, später auch zu gelingen.",
    stones: "Diamant, Bergkristall.",
    meditation: "Kerzen- und Feuerreinigung — konzentriere dich 10 bis 15 Minuten auf eine offene Flamme, um Ängste und fixe Gedanken loszulassen, bevor du den Monat planst.",
    relationships: "Bei Neumond ist es ungünstig, das Standesamt aufzusuchen oder ein Hochzeitsfest zu feiern; bleib lieber an einem ruhigen Ort und lass die Dinge auf dich wirken. Für die Planung einer Hochzeitszeremonie ist dagegen genau jetzt der beste Zeitpunkt.",
    business: "Nutze den Tag lieber, um den kommenden Monat zu skizzieren, statt etwas Neues zu starten. Entwirf deinen Businessplan und verschaffe dir einen Überblick über den Status quo, verschiebe aber Verhandlungen, größere Anschaffungen und finanzielle Entscheidungen, bis deine Energie zunimmt.",
    housework: "Beschränke dich auf leichtes Aufräumen in ruhiger Atmosphäre — Kerzen, sanfte Musik und Düfte wie Minze oder Sandelholz passen gut zu diesem Tag. Größere Putzaktionen, Reparaturen oder das Umstellen von Möbeln hebst du dir für später im Zyklus auf; plane für jetzt einfach die Hausprojekte des Monats.",
    activeOrgans: ["Kopf", "Gehirn", "Augen", "Nasennebenhöhlen"],
    doToday: ["Monatsvorsätze fassen", "Kerzenmeditation", "Locker planen"],
    avoidToday: ["Wichtige Entscheidungen", "Finanzgeschäfte", "Körperliche Anstrengung"],
    foodNote: "Nur leichte vegetarische Kost. Verzichte auf Scharfes, Fettiges oder anregende Speisen sowie auf Alkohol, Kaffee und Tee.",
    foodFavor: ["Leichte vegetarische Kost"],
    foodAvoid: ["Scharfe Speisen", "Fettige Speisen", "Alkohol", "Kaffee und Tee"],
    dreamFocus: "Skizze des kommenden Monats",
    dreamGuidance: "Träume können den kommenden Mondmonat vorzeichnen. Achte auf Wünsche, Pläne und aufbauende Bilder und nimm die hilfreichen davon in deine Neumond-Vorsätze auf.",
    dreamTiming: "Schlechte Träume sind heute Nacht selten — verstehe diesen Traum eher als groben Entwurf für den Monat als als feste Vorhersage.",
    dreamTip: "Notiere alles, was sich wie ein Plan oder ein Anfang angefühlt hat — die brauchbaren Teile lohnt es sich, in die Vorsätze dieses Monats einzubauen.",
    sourceUrl: "https://om-journal.com/moonday/1"
  },
  {
    lunarDay: 2,
    symbol: "Füllhorn",
    emoji: "🌾",
    tagline: "Aus dem Bauch heraus spürst du, was du wirklich brauchst — beim Essen wie im Umgang mit Menschen.",
    overview: "Ein guter Tag, um mit körperlichem Training oder einem größeren Lernprogramm zu beginnen. Iss nur, worauf du wirklich Appetit hast, und halte es im Umgang mit anderen genauso.",
    stones: "Jadeit, Chalcedon, Achat.",
    meditation: "Körperbewusstseins-Meditation — lege die Hände auf den Bauch und spüre, welche Speisen, Menschen oder Pläne dir wirklich guttun.",
    relationships: "Einer der besten Tage für eine Hochzeit; an diesem Tag geschlossene Verbindungen sind meist stabil und harmonisch. Zeig Verwandten deine Anteilnahme, verabrede dich und mach deinem Partner ein Geschenk.",
    business: "Ein starker Tag für materielle Angelegenheiten — Verhandlungen, Neueinstellungen, Projektstarts, die Suche nach Sponsoren oder Geschäftsreisen laufen meist glatt, besonders im Team.",
    housework: "Vertrau heute deiner Intuition: Fast jede Hausarbeit ist günstig, vom leichten Aufräumen bis zum großen Umräumen, auch das Umtopfen von Pflanzen. Traditionell galt dieser Tag auch als guter Zeitpunkt, um den Grundstein für ein neues Zuhause zu legen.",
    activeOrgans: ["Mund", "Rachen", "Zahnfleisch", "Nacken"],
    doToday: ["Wünsche laut aussprechen", "Neues beginnen", "Sich mit Fülle verbinden"],
    avoidToday: ["Negative Worte", "Fasten", "Streit"],
    foodNote: "Nahrhafte, großzügige Mahlzeiten. Milchprodukte und Getreide unterstützen die Energie dieses Tages. Vermeide es, hungrig zu bleiben.",
    foodFavor: ["Nahrhafte Mahlzeiten", "Milchprodukte", "Getreide"],
    foodAvoid: ["Hunger leiden"],
    dreamFocus: "Karmischer Bauplan",
    dreamGuidance: "Träume können auf wiederkehrende Lebensaufgaben oder karmische Verknotungen hinweisen. Nimm schwierige Bilder gelassen — sie zeigen oft, was in diesem Monat Aufmerksamkeit braucht.",
    dreamTiming: "Diese Träume funktionieren eher wie ein Bauplan für den Monat als wie eine wörtliche Vorhersage — ein unangenehmer oder leerer Traum ist nicht viel wert.",
    dreamTip: "Ein wiederkehrender oder seltsam vertrauter Traum weist oft auf ein altes Muster hin, das endlich bereit ist, sich aufzulösen.",
    sourceUrl: "https://om-journal.com/moonday/2"
  },
  {
    lunarDay: 3,
    symbol: "Leopard",
    emoji: "🐆",
    tagline: "Der Tag des Kämpfers, der Tag der Tat.",
    overview: "Ein sehr energiegeladener Tag. Jetzt ist Handeln gefragt — Abwarten ist nicht empfehlenswert, und intensives körperliches Training passt gut.",
    stones: "Rubin, Pyrit, Aventurin.",
    meditation: "Kampfkunst und Körperentspannung — löse Anspannung und alten Ärger, indem du nacheinander durch jeden Körperteil hindurch atmest.",
    relationships: "Der dritte Mondtag ist ungünstig für eine Hochzeit; wenn du die Zeremonie trotzdem an diesem Tag hältst, gestalte sie außergewöhnlich. Vermeide scharfe Worte — dein Partner braucht heute Zärtlichkeit, kein Missfallen.",
    business: "Die Energie ist hoch und begünstigt mutiges, entschlossenes Handeln — geh voran und geh kalkulierte Risiken ein. Lass jedoch die Finger von Finanzgeschäften, Verluste sind heute wahrscheinlich.",
    housework: "Eher etwas für körperlich fordernde Aufgaben als für kleine Handgriffe; traditionell ein guter Tag für Metallarbeiten, das Schärfen von Klingen und das Reparieren von Schmuck. Halte dein Temperament im Zaum, damit aus Einsatz kein Schaden wird.",
    activeOrgans: ["Schultern", "Arme", "Hände", "Gelenke"],
    doToday: ["Körperliche Aktivität", "Grenzen setzen", "Mut zeigen"],
    avoidToday: ["Passives Abwarten", "Neue Beziehungen beginnen", "Übermäßigen Genuss"],
    foodNote: "Energiespendende Speisen. Halte die Portionen moderat; vermeide übermäßiges oder schweres Essen.",
    foodFavor: ["Energiespendende Speisen", "Moderate Portionen"],
    foodAvoid: ["Übermäßiges Essen", "Schwere Mahlzeiten"],
    dreamFocus: "Energie und Mut",
    dreamGuidance: "Träume können zeigen, wie deine Energie fließt. Kampf-, Widerstands- oder Siegesbilder geben Aufschluss über deine innere Kraft.",
    dreamTiming: "Träume gehen an diesem Mondtag selten in Erfüllung, sind aber trotzdem lesenswert dafür, was sie über dich zeigen.",
    dreamTip: "Achte darauf, wofür du im Traum Energie einsetzt — das spiegelt meist, wohin deine tatsächliche Kraft gerade fließt, im Guten wie im Schlechten.",
    sourceUrl: "https://om-journal.com/moonday/3"
  },
  {
    lunarDay: 4,
    symbol: "Baum der Erkenntnis",
    emoji: "🌳",
    tagline: "Der Tag der Entscheidung zwischen Gut und Böse — in Taten wie in Gedanken.",
    overview: "Zeit für dich allein. Gartenarbeit, Hausarbeit, Spaziergänge, Entspannung und der Kontakt mit der Natur sind heute günstig, Teamarbeit und übereilte Entscheidungen dagegen nicht.",
    stones: "Sardonyx, Amazonit, grüner Nephrit.",
    meditation: "Mantra-Singen und Zeit in der Natur — ein Spaziergang draußen oder das Singen von „AUM“ hilft, die unsichere Energie des Tages zu erden.",
    relationships: "Plane heute keine Hochzeitszeremonie, und erwäge, ein romantisches Date abzusagen, wenn dir wichtige Ergebnisse am Herzen liegen. Unbedachte oder verletzende Worte fallen jetzt leicht — wähle sie mit Bedacht.",
    business: "Noch ist nichts endgültig festgelegt, daher lassen sich frühere Fehler dieses Monats noch korrigieren — überprüfe deine Finanzen, verfeinere deine Methoden und handle nur vor Mittag. Beginne nichts Neues und erwarte keine schnellen Erfolge.",
    housework: "Gut geeignet für praktische Reparaturen, besonders alles aus Holz — Türen, Gardinenstangen, Schneidebretter und Erbstücke profitieren jetzt von Ölen, Lüften oder sanfter Restaurierung. Überleg es dir zweimal, bevor du heute etwas wegwirfst.",
    activeOrgans: ["Magen", "Verdauungssystem", "Brust"],
    doToday: ["Nach Weisheit suchen", "Stille Reflexion", "Sorgfältig planen"],
    avoidToday: ["Übereilte Entscheidungen", "Streit", "Große neue Vorhaben beginnen"],
    foodNote: "Einfache, reine Speisen. Vermeide Übermaß; heute zählen Zurückhaltung und Klarheit.",
    foodFavor: ["Einfache Speisen", "Reine Speisen"],
    foodAvoid: ["Übermaß und Völlerei"],
    dreamFocus: "Warnungen und ererbte Muster",
    dreamGuidance: "Träume können in Erfüllung gehen, besonders lebhafte. Verworrene Bilder bitten darum, Pläne zu überarbeiten; Verwandte im Traum können auf ererbte Muster hinweisen, die Pflege brauchen.",
    dreamTiming: "Träume können sich heute erfüllen, besonders die mit kräftigen Farben.",
    dreamTip: "Verwirrende, verworrene Bilder sind ein Wink, einen Plan zu überdenken; ein häufig auftauchendes Familienmitglied weist meist auf ein ererbtes Muster hin, das Beachtung verdient.",
    sourceUrl: "https://om-journal.com/moonday/4"
  },
  {
    lunarDay: 5,
    symbol: "Einhorn",
    emoji: "🦄",
    tagline: "Bleib dir treu — Alchemie von Seele und Mahlzeit.",
    overview: "Alles gelingt, wenn du kreativ bist und dich auf dein Ziel konzentrierst. Bleib deinen Prinzipien, Gefühlen und Empfindungen treu.",
    stones: "Türkis, rosa Chalcedon, Marmor.",
    meditation: "Meditation beim Essen — achtsam und langsam genießen.",
    relationships: "Zeit für Veränderungen, unerwartete Entdeckungen und Offenbarungen. Für Paare, die noch nicht viel Zeit miteinander verbracht haben, ist dies kein günstiger Tag, um eine Familie zu gründen.",
    business: "Gut geeignet, um Schulden zu begleichen, Angefangenes fertigzustellen und grundlegende Änderungen an deiner Arbeitsweise vorzunehmen — vermeide aber neue Projekte und direkte Geldgeschäfte. Chefs und Partner können sich heute unerwartet stur zeigen.",
    housework: "Lass die reguläre Reinigung heute sein und kümmere dich stattdessen um die Vorratskammer — fülle Lebensmittel auf und ordne, was schon da ist, koch nach Gefühl statt nach Routine.",
    activeOrgans: ["Speiseröhre", "Brust", "Drittes Auge (Ajna)"],
    doToday: ["Angefangene Projekte beenden", "Schulden begleichen", "Achtsam kochen"],
    avoidToday: ["Fasten", "Wertsachen verlieren", "Neue Finanzgeschäfte"],
    foodNote: "Milchprodukte, Obst, Honig. Verzichte auf Fleisch, Nüsse, fermentierte Speisen, Getreide, Samen und Alkohol. Iss nicht zu viel.",
    foodFavor: ["Milchprodukte", "Obst", "Honig"],
    foodAvoid: ["Fleisch", "Nüsse", "Fermentierte Speisen", "Getreide und Samen", "Alkohol"],
    dreamFocus: "Gesundheit und Bewegung",
    dreamGuidance: "Gute Träume sind vielversprechend, beunruhigende bitten um Fürsorge für Gesundheit und Energie. Wege, Bewegung und sogar Weinen können positive Zeichen sein.",
    dreamTiming: "Gute Träume können in Erfüllung gehen; beunruhigende sind eher ein Hinweis zum Hinschauen als ein Grund zur Sorge.",
    dreamTip: "Weinen im Traum gilt heute als gutes Zeichen, und ein offener Weg spiegelt meist echten Fortschritt wider.",
    sourceUrl: "https://om-journal.com/moonday/5"
  },
  {
    lunarDay: 6,
    symbol: "Kranich",
    emoji: "🦢",
    tagline: "Atem und Klang können jede Krankheit heilen.",
    overview: "Ein Tag der Stille und Bescheidenheit. Die Intuition ist geschärft, und Atemübungen jeder Art, auch Aromatherapie, tun heute gut.",
    stones: "Hyazinth, Citrin.",
    meditation: "Atem- und Klangtherapie — lausche den Klängen der Natur, Wind, Vogelgesang oder Regen, als eine Form der Meditation.",
    relationships: "Dieser Tag kann einer neuen Familie Frieden und Beständigkeit schenken; heute geschlossene Verbindungen finden meist zu Weisheit und halten die Liebe langfristig. Venus hat Einfluss, was den Tag gut für Verabredungen macht.",
    business: "Ein durchweg günstiger Tag, um Dinge zu erledigen und deine Fähigkeiten zu zeigen, auch für die Klärung finanzieller Angelegenheiten — verleihe nur kein Geld, erzwinge keine Ergebnisse und arbeite nicht bis zur Erschöpfung.",
    housework: "Die ruhige, sanfte Energie passt gut zum Lüften von Räumen, zum Öffnen der Vorhänge für die Sonne und zum Abwischen von Oberflächen. Bleib bei deinem gewohnten Rhythmus, statt Neues zu beginnen, und behalte deine Sachen lieber, statt sie herzugeben.",
    activeOrgans: ["Dickdarm", "Bauch", "Unterer Verdauungstrakt"],
    doToday: ["Vor dem Schlafen eine klare Frage stellen", "Intuitive Selbstfürsorge", "Sanfte Bewegung"],
    avoidToday: ["Traumbilder weit herumerzählen", "Ärger oder Konflikte", "Überanstrengung"],
    foodNote: "Leichte, reinigende Speisen. Ein sanfter Tag für Ernährungsumstellungen und die Pflege der Verdauung.",
    foodFavor: ["Leichte Speisen", "Reinigende Speisen"],
    foodAvoid: ["Schwere Speisen"],
    dreamFocus: "Private Offenbarung",
    dreamGuidance: "Träume können Antworten bringen, sollten aber für dich bleiben. Stell vor dem Einschlafen eine klare Frage und schreib die Bilder sofort nach dem Aufwachen auf.",
    dreamTiming: "Diese Träume können sich erfüllen — der Überlieferung nach allerdings nur, wenn du sie für dich behältst.",
    dreamTip: "Achte auf alles, was im Traum unerledigt bleibt — es weist oft auf eine Aufgabe hin, die im wachen Leben noch auf dich wartet.",
    sourceUrl: "https://om-journal.com/moonday/6"
  },
  {
    lunarDay: 7,
    symbol: "Windrose",
    emoji: "🧭",
    tagline: "Sag nichts Unbedachtes — achte auf die Reinheit deiner Worte.",
    overview: "Worte haben heute eine besondere Kraft, und was du sagst, kann leicht Wirklichkeit werden. Lüge nicht und plaudere nicht ohne Sinn — schweige lieber.",
    stones: "Saphir, Heliotrop, Koralle.",
    meditation: "Achtsames Sprechen und Affirmation — sprich sparsam, und wenn du sprichst, wähle deine Worte, Gebete oder Mantras mit Bedacht, denn sie tragen heute ungewöhnliche Kraft.",
    relationships: "Für kreative Menschen ist dieser Tag ideal, um eine Familie zu gründen, mit tiefer Verbundenheit als Basis der Beziehung. Alles, was heute gesagt wird, kann wahr werden — lass liebevolle Worte das Thema des Gesprächs sein.",
    business: "Günstig für Verhandlungen, neue Kontakte, den Start einer Werbekampagne oder ein Vorstellungsgespräch — lobe dein Team großzügig. Übertreibe deine Sache aber nicht und lass keinen Zweifel in deine Argumentation einfließen. Der Tag begünstigt Angelegenheiten, die sich schnell abschließen lassen, weniger langwierige Geschäfte.",
    housework: "Ein guter Tag, um liegen gebliebene Projekte fertigzustellen — arbeite zu ruhigen Klängen wie Gesängen, Mantras oder Klangschalen statt lauter Musik. Bevorzuge kreative Aufgaben wie Keramik gegenüber allem Zerstörerischen und halte deine Gedanken positiv, während du arbeitest.",
    activeOrgans: ["Hals", "Schilddrüse", "Stimmbänder", "Nacken"],
    doToday: ["Deinen Zweck aussprechen", "Reisen unternehmen oder planen", "Deine Wahrheit sagen"],
    avoidToday: ["Leeres Geschwätz", "Scharfe oder unbedachte Worte", "Sich zu viel vornehmen"],
    foodNote: "Abwechslungsreiche, maßvolle Mahlzeiten. Warme Flüssigkeiten und Kräutertees tun dem Hals gut.",
    foodFavor: ["Abwechslungsreiche, maßvolle Mahlzeiten", "Warme Flüssigkeiten", "Kräutertees"],
    foodAvoid: [],
    dreamFocus: "Worte und Bestimmung",
    dreamGuidance: "Achte besonders auf gesprochene Worte in deinen Träumen. Sie können nützliche Hinweise zu deiner Richtung enthalten, auch wenn sich die Erfüllung Zeit lässt.",
    dreamTiming: "Träume heute Nacht können wirklich nützliche Informationen tragen, nicht nur Rauschen.",
    dreamTip: "Achte genau auf gesprochene Worte im Traum — das Unterbewusstsein spricht heute eher in Sprache als in bloßen Bildern.",
    dreamRemedy: "Wenn dich ein Traum beunruhigt, erzähl ihn leise fließendem Wasser, einem Wasserhahn oder einem Bach, um das Gefühl loszulassen.",
    sourceUrl: "https://om-journal.com/moonday/7"
  },
  {
    lunarDay: 8,
    symbol: "Phönix",
    emoji: "🔥",
    tagline: "Ein Tag der Umkehr, der Reinigung und der Wandlung.",
    overview: "Ein aktiver Tag, an dem Unvorhergesehenes passieren kann. Ein guter Tag, um über dein Leben nachzudenken; von Baden, Wäschewaschen und Alkohol wird abgeraten.",
    stones: "Roter Granit, Chrysolith, Morion.",
    meditation: "Feuerreinigung — setz dich an eine Flamme, um negative Gefühle loszulassen, und reinige anschließend dein Zuhause im Kerzenlicht.",
    relationships: "Versuch, heute keine Familie zu gründen, auch wenn jetzt geschlossene Verbindungen gut zu aktiven, reisefreudigen Paaren passen können. Menschen sind heute offenherzig — verzichte auf Sarkasmus und Boshaftigkeit.",
    business: "Lose Enden aus der letzten Zeit lassen sich jetzt nicht mehr ignorieren, und Überraschungen oder Reibungen können auftauchen — kümmere dich nur um kleinere Finanzangelegenheiten, such nach kreativen Lösungen statt nach neuen Partnern und nimm dir nicht mehr vor, als du tragen kannst.",
    housework: "Halte Wasser heute lieber auf Abstand — verzichte auf Wischen, Wäschewaschen und das Abwischen von Oberflächen mit einem feuchten Tuch. Auch feuerbezogene Arbeiten und alles mit Erde meidest du besser.",
    activeOrgans: ["Herz", "Brust", "Oberer Rücken", "Wirbelsäule"],
    doToday: ["Alte Muster loslassen", "Kreative Neuerfindung", "Wandlungspraktiken"],
    avoidToday: ["An der Vergangenheit festhalten", "Emotionale Extreme", "Leichtsinniges Handeln"],
    foodNote: "Wärmende, herzstärkende Speisen. Verzichte auf Aufputschmittel und Alkohol.",
    foodFavor: ["Wärmende Speisen", "Herzstärkende Speisen"],
    foodAvoid: ["Aufputschmittel", "Alkohol"],
    dreamFocus: "Wandlung",
    dreamGuidance: "Träume können ungenutzte Gaben, alte, unerledigte Probleme oder deine Bereitschaft zur Veränderung zeigen. Weite Räume deuten auf Bewegung hin, Sackgassen bitten um Erneuerung.",
    dreamTiming: "Träume heute Nacht zeigen dir meist genau, wofür du bereit bist, dich zu verändern.",
    dreamTip: "Offene, weite Umgebungen im Traum deuten auf echten Fortschritt hin; enge oder blockierte Orte zeigen, wo du dich noch feststeckst fühlst.",
    sourceUrl: "https://om-journal.com/moonday/8"
  },
  {
    lunarDay: 9,
    symbol: "Fledermaus",
    emoji: "🦇",
    tagline: "Sei wachsam — unterscheide, wann dunkle Kräfte verführen und wann das Licht der Wahrheit scheint.",
    overview: "In diesen 24 Stunden haben negative Einflüsse Macht über die Menschen. Ein Tag der Provokationen — hüte dich vor Täuschung, Versuchung, Verführung und Illusion.",
    stones: "Schwarze Perle, Alexandrit, Rauchtopas, Ophit.",
    meditation: "Schutz durch weißes Licht — an diesem heiklen Tag ist eine einfache Visualisierung von weißem Licht besser geeignet als tiefe Meditation; Räuchern oder Glocken klären das Zuhause.",
    relationships: "Der ungünstigste Tag für Hochzeitszeremonien; Konflikte zwischen Partnern sind heute häufig. Versuch, ein erstes Date abzusagen, und halte negative Gefühle im Zaum.",
    business: "Kein Tag für neue Vorhaben — pass gut auf deine Wertsachen auf, denn das Risiko von Verlust oder Diebstahl ist heute hoch. Ruh dich aus, kehr nach innen und verzichte auf Verträge, Kredite oder große Präsentationen.",
    housework: "Passt zu lange schon begonnenen Projekten, die noch mehr Zeit brauchen, etwa Bauen, Umbauten oder Pflanzarbeiten. Behandle das Putzen wie eine Meditation, dann zahlt sich der Einsatz leise aus — bei Holzarbeiten und mechanischen Reparaturen besteht heute allerdings erhöhte Verletzungsgefahr.",
    activeOrgans: ["Nieren", "Unterer Rücken", "Nebennieren"],
    doToday: ["Verborgenen Wahrheiten ins Auge sehen", "Innere Einkehr", "Ruhen und erholen"],
    avoidToday: ["Wichtige Entscheidungen", "Neuanfänge", "Provozierende Situationen"],
    foodNote: "Nierenstärkende Speisen: wasserreiches Gemüse, Gerste, warme Suppen. Verzichte auf Salz und Alkohol.",
    foodFavor: ["Wasserreiches Gemüse", "Gerste", "Warme Suppen"],
    foodAvoid: ["Salz", "Alkohol"],
    dreamFocus: "Verborgener Konflikt",
    dreamGuidance: "Träume können intensiv oder unangenehm sein, weil verborgene Konflikte an die Oberfläche kommen. Zieh die Lehre daraus und lass die schweren Bilder dann los.",
    dreamTiming: "Diese Träume können echtes Unbehagen auslösen — versuch, die einzelnen Bilder nicht zu wörtlich zu nehmen.",
    dreamTip: "Wenn sich ein Traum wie eine Warnung anfühlt, versteh ihn als Hinweis auf eine Spannung, die einen Namen verdient, nicht als Vorhersage, vor der du dich fürchten musst.",
    sourceUrl: "https://om-journal.com/moonday/9"
  },
  {
    lunarDay: 10,
    symbol: "Brunnen",
    emoji: "⛲",
    tagline: "Stärke dein Zuhause — vergiss deine Wurzeln nicht.",
    overview: "Heute lenkst du deine Schritte auf die Stärkung familiärer Bande. Pflege Familientraditionen, und grundlegende Vorhaben wie Hausbau oder -reparatur sind begünstigt. In mehreren Mondtraditionen gilt dieser Tag zudem als einer der günstigsten des Monats für große Vorhaben und bedeutende Anschaffungen.",
    stones: "Bernstein, Sardonyx.",
    meditation: "Ahnen- und Familienmeditation — verbinde dich mit deiner Abstammungslinie, bitte um ihre Weisheit oder teile eine Mahlzeit mit Verwandten.",
    relationships: "Der zehnte Mondtag ist der günstigste, um eine Familie zu gründen und zu heiraten; heute geschlossene Verbindungen neigen zu Stabilität, Liebe und Respekt. Auch ein guter Tag, um die Familie des Partners kennenzulernen.",
    business: "Begünstigt das Familienunternehmen, die Regelung der Haushaltsfinanzen und die Stärkung bestehender Arbeitsbeziehungen — beruflicher Erfolg stellt sich diese Woche leicht ein, auch wenn es nicht der Tag ist, um etwas völlig Neues zu starten.",
    housework: "Einer der besten Tage für größere Projekte rund ums Haus — Reparaturen, Grundreinigung, Neuordnung, sogar das Pflanzen von Obstbäumen für eine dauerhafte Ernte. Beziehe die ganze Familie ein, aber bewahre den Frieden, denn Streit wiegt heute besonders schwer.",
    activeOrgans: ["Gelenke", "Bindegewebe", "Rücken", "Wirbelsäule"],
    doToday: ["Familie und Ahnen ehren", "Dankbarkeit zeigen", "Großzügig geben"],
    avoidToday: ["Egoismus", "Verschwendung", "Wichtige Traditionen brechen"],
    foodNote: "Nahrhafte, traditionelle Speisen. Großzügige Mahlzeiten sind günstig; teile das Essen mit anderen.",
    foodFavor: ["Nahrhafte, traditionelle Speisen", "Großzügige Mahlzeiten", "Essen teilen"],
    foodAvoid: [],
    dreamFocus: "Familienlinie",
    dreamGuidance: "Träume können Themen rund um Familie, Abstammung oder Vorfahren tragen. Helle Träume dürfen leicht und symbolisch bleiben; belastende Träume solltest du anerkennen und loslassen.",
    dreamTiming: "Familienmitglieder und Ahnen tauchen heute Nacht häufig in Träumen auf.",
    dreamTip: "Ein auftauchender Verwandter oder Ahne bietet meist eher Unterstützung oder Einsicht für deinen eigenen Weg als eine wörtliche Botschaft über sich selbst.",
    sourceUrl: "https://om-journal.com/moonday/10"
  },
  {
    lunarDay: 11,
    symbol: "Kundalini",
    emoji: "🐍",
    tagline: "Das Erwachen der Urenergie, genannt Kundalini. Der Tag von Ekadashi.",
    overview: "Der energiegeladenste Tag. Heute ist bei jeder Aufgabe Vorsicht und Aufmerksamkeit gefragt, und was du heute beginnst, solltest du auch zu Ende bringen.",
    stones: "Feueropal, Hämatit, Karneol.",
    meditation: "Kundalini- und inneres-Feuer-Meditation — begünstigt Fasten, Rückzug und die Arbeit mit den Chakren, um schlummernde Energie zu wecken.",
    relationships: "Dieser Mondtag ist günstig, um eine Familie zu gründen, auch wenn die Energie sehr hoch ist und übermäßiger Alkoholgenuss bei einer Hochzeitsfeier vermieden werden sollte. Kümmere dich um deinen Partner und mach lieber ein Geschenk, als über Zukunftspläne zu grübeln.",
    business: "Einer der energiereichsten und erfolgreichsten Tage des Monats — bring Laufendes zum Abschluss, unterschreib Verträge, übernimm neue Verantwortung und bereite dich gründlich auf Kommendes vor. Verbeiß dich nur nicht zu sehr in materiellen Gewinn.",
    housework: "Beginne nur, was du auch wirklich zu Ende bringen willst — dieser Tag passt zu Bauprojekten mit einer festen Frist. Teile dir deine Kräfte beim Putzen gut ein, um nicht auszupowern, und sei vorsichtig mit scharfen Werkzeugen.",
    activeOrgans: ["Beine", "Waden", "Durchblutung", "Feinstoffliche Energiekanäle"],
    doToday: ["Meditation und Energiearbeit", "Kreative oder spirituelle Arbeit", "Yoga oder Bewegung"],
    avoidToday: ["Jede Art von Exzess", "Impulsive Ausgaben", "Energie durch Streit verschwenden"],
    foodNote: "Leichte, sattvische Speisen. Verzichte auf Fleisch und Aufputschmittel. Wenn du dich danach fühlst, ist Fasten heute gut unterstützt.",
    foodFavor: ["Leichte, sattvische Speisen", "Fasten"],
    foodAvoid: ["Fleisch", "Aufputschmittel"],
    dreamFocus: "Balance von Materie und Geist",
    dreamGuidance: "Träume können zeigen, ob sich dein materielles und dein spirituelles Leben im Gleichklang bewegen. Deine eigene Rolle im Traum ist dabei der entscheidende Hinweis.",
    dreamTiming: "Ein bedeutsamer Traum heute Nacht kann sich innerhalb von etwa drei Tagen im wachen Leben zeigen.",
    dreamTip: "Achte darauf, ob der Traum eher zur materiellen oder zur spirituellen Welt neigt — genau diese Balance ist die eigentliche Botschaft.",
    sourceUrl: "https://om-journal.com/moonday/11"
  },
  {
    lunarDay: 12,
    symbol: "Herz",
    emoji: "❤️",
    tagline: "Liebe kann das Herz öffnen.",
    overview: "Gefühle von Liebe, Mitgefühl und Nächstenliebe sind heute besonders aktiv. Beten und das Klären deiner Gedanken sind günstig, und dies ist ein idealer Tag für eine Hochzeit.",
    stones: "Lasurit, gelbe Koralle, Perlmutt, rosa Perle.",
    meditation: "Wasser- und Herzmeditation — setz dich an fließendes Wasser, oder lausche seinem Klang, und lass deine Gefühle zur Ruhe kommen.",
    relationships: "Einer der besten Tage, um für Partner jeden Alters eine Familie zu gründen; am zwölften Mondtag geschlossene Verbindungen sind meist von Glück begleitet und enden selten in Scheidung. Kümmere dich besonders liebevoll um deinen Partner und vermeide es, ihn zu kränken.",
    business: "Ein ruhiger, sanfter Tag für Verhandlungen, um Hilfe zu bitten, Konflikte ehrlich zu klären und sich um Finanzen oder Wohltätigkeit zu kümmern. Vermeide Überarbeitung und den Start ambitionierter Vorhaben.",
    housework: "Besser in Menschen investiert als in Hausarbeit — lass die Putzliste heute liegen und wende deine Energie stattdessen älteren Verwandten oder geliebten Menschen zu. Kleine Aufmerksamkeiten wie eine Tasse Tee oder das Verschenken von Nicht-mehr-Gebrauchtem zählen heute mehr als Sauberkeit.",
    activeOrgans: ["Herz", "Herz-Kreislauf-System", "Brust", "Blut"],
    doToday: ["Liebevolle und mitfühlende Taten", "Herzzentrierte Reflexion", "Geben und Nehmen"],
    avoidToday: ["Streit und Grausamkeit", "Überarbeitung", "Gefühle unterdrücken"],
    foodNote: "Herzstärkende Speisen: Beeren, Blattgemüse, dunkle Schokolade. Vermeide übermäßig gesättigte Fette.",
    foodFavor: ["Beeren", "Blattgemüse", "Dunkle Schokolade"],
    foodAvoid: ["Übermäßig gesättigte Fette"],
    dreamFocus: "Werte",
    dreamGuidance: "Träume können zeigen, ob materielle oder spirituelle Werte gerade dominieren. Helle, gut erinnerte Träume verdienen besondere Aufmerksamkeit.",
    dreamTiming: "Ein guter Traum heute Nacht kann sich innerhalb von etwa einer Woche im wachen Leben zeigen.",
    dreamTip: "Was oder wer im Traum am wichtigsten erscheint, spiegelt meist recht genau, was dir gerade tatsächlich am Herzen liegt.",
    sourceUrl: "https://om-journal.com/moonday/12"
  },
  {
    lunarDay: 13,
    symbol: "Rad",
    emoji: "☸️",
    tagline: "Das Rad dreht sich, die Bewegung geht weiter.",
    overview: "Ein guter Tag für Teamarbeit, das Aneignen neuen Wissens und den Start neuer Lernzyklen. Nutze den Tag zum Ansammeln und Herstellen von Haushaltsgegenständen; Brotbacken ist empfehlenswert.",
    stones: "Edelopal.",
    meditation: "Meditation des Erneuerungsrads — visualisiere, wie du ein sich wiederholendes Muster in deinem Leben durchbrichst, um alte gedankliche Blockaden zu lösen.",
    relationships: "Ein günstiger Tag, um für Wissenschaftler, Reisende, Geologen und Forscher eine Familie zu gründen. An diesem Mondtag geschlossene Verbindungen sind meist umsichtig, diszipliniert und gut durchdacht.",
    business: "Günstig, um deinen Wirkungskreis zu erweitern, Kurskorrekturen vorzunehmen, Verträge zu unterschreiben, Personal einzustellen oder etwas Neues zu lernen — verlass dich bei ernsteren Dingen eher auf dein Team als auf dich allein, und lass Laufendes nicht fallen.",
    housework: "Der Tag teilt sich in zwei Hälften — bleib ausgeglichen und überleg, bevor du dich auf etwas festlegst. Günstig sind runde, wiederkehrende Arbeiten — einen Brunnen bauen, Garn spinnen, runde Brote backen — angegangen ohne Eile.",
    activeOrgans: ["Fortpflanzungssystem", "Becken", "Unterbauch"],
    doToday: ["Alte Kreisläufe durchbrechen", "Wiederkehrende Muster überdenken", "Bewusste Veränderung suchen"],
    avoidToday: ["Alte Fehler wiederholen", "Dinge halb fertig lassen", "Selbstzufriedenheit"],
    foodNote: "Leichte, reinigende Mahlzeiten. Vermeide Übermaß. Frisches Gemüse und Säfte unterstützen die Energie des Musterdurchbrechens.",
    foodFavor: ["Leichte, reinigende Mahlzeiten", "Frisches Gemüse", "Säfte"],
    foodAvoid: ["Übermaß"],
    dreamFocus: "Kreisläufe durchbrechen",
    dreamGuidance: "Träume können zeigen, wo du dich in einer Schleife wiederholst und wo Veränderung möglich ist. Halte sie rasch fest — Warnungen können sich bald zeigen.",
    dreamTiming: "Ein Traum heute Nacht kann als Warnung wirken und sich innerhalb von etwa acht Tagen bewahrheiten.",
    dreamTip: "Schreib ihn sofort nach dem Aufwachen auf — in dieser Nacht verblasst die Bedeutung schnell, sobald der Tag beginnt.",
    sourceUrl: "https://om-journal.com/moonday/13"
  },
  {
    lunarDay: 14,
    symbol: "Zwei Flöten",
    emoji: "🎵",
    tagline: "Die Trompete ruft dazu auf, Dinge von großer Bedeutung zu beginnen.",
    overview: "Dieser Tag bringt Glück für Neuanfänge, und heute gestartete Projekte tendieren dazu, aus eigener Kraft zu gelingen. Es besteht eine starke Verbindung zu Wissen und Studium.",
    stones: "Hyazinth.",
    meditation: "Heilige-Klang-Meditation — singe „OM“ oder „AUM“ und erwäge, einen neuen Mantra-Zyklus oder eine 40-Tage-Praxis zu beginnen.",
    relationships: "Ein günstiger Tag, um für Paare mit langer vorehelicher Beziehung eine Familie zu gründen, ebenso eine gute Zeit für Geschiedene, um noch einmal neu zu beginnen. Bei einer Verabredung sind Menschen oft schüchtern — hör also gut hin, was unausgesprochen bleibt.",
    business: "Gut für entschlossenes, wichtiges Handeln — einer der günstigsten Tage für Karriereschritte, Gehaltserhöhungen und Anerkennung. Teile deine Ideen morgens öffentlich mit und kümmere dich um Finanzielles, verschwende den Schwung aber nicht mit Untätigkeit.",
    housework: "Ein starker Tag, um deinen Wohnraum energetisch zu reinigen — arbeite mit den vier Elementen Salz, Räucherwerk, Wasser und Kerzen, oder wische einfach mit gesalzenem Wasser, während eine Kerze brennt, um stehende Energie zu lösen.",
    activeOrgans: ["Füße", "Lymphsystem", "Unterkörper", "Immunsystem"],
    doToday: ["Musik und kreative Künste", "Verborgene Talente entwickeln", "Sanfte spirituelle Praxis"],
    avoidToday: ["Überanstrengung", "Konfrontationen", "Übermäßiges Essen oder Trinken"],
    foodNote: "Maßvolle, ausgewogene Ernährung. Ausreichend zu trinken ist heute besonders wichtig.",
    foodFavor: ["Ausgewogene Ernährung", "Ausreichend Flüssigkeit"],
    foodAvoid: [],
    dreamFocus: "Verborgene Fähigkeiten",
    dreamGuidance: "Träume sind heute meist nicht prophetisch, können aber Fähigkeiten offenbaren, die es zu entwickeln gilt. Schwere Träume darfst du leichten Herzens loslassen.",
    dreamTiming: "Träume heute Nacht bedeuten für sich genommen selten viel.",
    dreamTip: "Taucht etwas Beunruhigendes auf, lass es los — es weist eher auf ein unentwickeltes Talent hin als auf eine echte Warnung.",
    sourceUrl: "https://om-journal.com/moonday/14"
  },
  {
    lunarDay: 15,
    symbol: "Feuerdrache",
    emoji: "🐉",
    tagline: "Askese und Selbstdisziplin.",
    overview: "Heute ist Vollmond, ein Tag mit hoher Energie. Die Versuchung, nachzugeben oder träge zu werden, ist groß — halte deine Leidenschaften im Zaum und stärke deine Selbstdisziplin.",
    stones: "Achat, Morion, Gagat.",
    meditation: "Stille Meditation — sitze bei stärkstem Mondlicht ruhig da und lass Gedanken wie Wolken vorüberziehen, ohne deine Ruhe zu stören.",
    relationships: "Ein sehr anspruchsvoller Mondtag; nur reife und erfahrene Partner haben gute Chancen, jetzt eine Familie zu gründen. Junge, noch nicht bereite Paare könnten enttäuscht werden, und für eine Verabredung ist dieser Tag ungünstig.",
    business: "Halte es einfach — leichter Handel ist in Ordnung, doch vermeide ambitionierte Schritte, große Verhandlungen oder das Abgeben von Verantwortung. Halte an ungewöhnlichen Ideen fest, die jetzt auftauchen, und nutze den Nachmittag, der mehr Raum für kreative Umsetzung bietet als der Vormittag.",
    housework: "Die Stimmung schwankt heute zwischen leicht und schwer — plane also sanft statt anspruchsvoll: Räume lüften, befeuchten oder Kerzen anzünden reicht völlig. Halte den Umgang ruhig und dräng Familienmitglieder nicht zu ihren Entscheidungen.",
    activeOrgans: ["Leber", "Gallenblase", "Ganzer Körper auf dem Energiehöhepunkt"],
    doToday: ["Feiern und dich ausdrücken", "Über den bisherigen Zyklus nachdenken", "Vollmondritual"],
    avoidToday: ["Alkohol", "Übermäßiges Essen", "Hitzige Streitgespräche"],
    foodNote: "Leberstärkende Speisen: Rote Bete, Bitterstoffe, Artischocke. Verzichte unbedingt auf Alkohol und schwere Fette.",
    foodFavor: ["Rote Bete", "Bittere Blattgemüse", "Artischocke"],
    foodAvoid: ["Alkohol", "Schwere Fette"],
    dreamFocus: "Unbewusstes Wetter",
    dreamGuidance: "Träume spiegeln deinen aktuellen inneren Zustand. Helle Träume können prophetisch sein, wenn du sie für dich behältst; schwere Träume deuten auf ein Ungleichgewicht und die Aufgaben des nächsten Zyklus hin.",
    dreamTiming: "Der Traum heute Nacht spiegelt eher deinen momentanen Gefühlszustand als die Zukunft.",
    dreamTip: "Ein guter Traum hält sich eher, wenn du ihn für dich behältst; ein schwerer zeigt dir nur, wo die Energie dieses Monats noch ins Gleichgewicht will.",
    sourceUrl: "https://om-journal.com/moonday/15"
  },
  {
    lunarDay: 16,
    symbol: "Schmetterling",
    emoji: "🦋",
    tagline: "Harmonie und Gleichgewicht von Körper und Geist.",
    overview: "Halte dein Gleichgewicht — Übungen, die die Balance fördern, sind heute empfehlenswert. Ein guter Tag zum Putzen, Aufräumen und für ein rituelles Bad.",
    stones: "Spinell, Turmalin, Charoit, Smaragd, Perle (außer schwarzer Perle).",
    meditation: "Mondlicht-Meditation — visualisiere sanftes weißes Licht, das den Körper erfüllt und beruhigt, um Gleichgewicht und Schönheit wiederherzustellen.",
    relationships: "Weder das Gründen einer Familie noch eine Hochzeitszeremonie sind heute empfehlenswert, wohl aber der Start der Flitterwochen oder ein Heiratsantrag. Ein romantisches Treffen gelingt gut an einem ruhigen, friedlichen Ort.",
    business: "Ein Tag, um dich von der letzten Anstrengung zu erholen und Leichtes fertigzustellen, statt Schweres zu beginnen — festige, was du bereits erreicht hast. Verzichte auf Unterschriften, Finanzgeschäfte und darauf, Vorgesetzte um Gefallen zu bitten.",
    housework: "Begünstigt sanfte, kreative Projekte im Haus — Stickerei, Zeichnen, Blumenarrangements — mehr als jede echte Anstrengung. Gartenarbeit, das Sortieren der Garderobe oder die Wahl von Schmuck passen ebenfalls zur erholsamen Stimmung nach dem Vollmond.",
    activeOrgans: ["Nieren", "Haut", "Unterer Rücken", "Lymphe"],
    doToday: ["Schönheitsrituale", "Künstlerischer Ausdruck", "Loslassen"],
    avoidToday: ["Scharfe Worte", "Entscheidungen in starker Erregung", "Übermäßigen Genuss"],
    foodNote: "Leicht und reinigend. Nierenstärkende Wahl: Gurke, Wassermelone, Zitronenwasser.",
    foodFavor: ["Gurke", "Wassermelone", "Zitronenwasser"],
    foodAvoid: ["Schwere Speisen"],
    dreamFocus: "Reinigung und Balance",
    dreamGuidance: "Träume helfen, Anspannung zu lösen und Gleichgewicht wiederherzustellen. Albträume lassen sich als Reinigung der Psyche von altem Druck verstehen, nicht als schlechtes Omen.",
    dreamTiming: "Träume heute Nacht wirken schnell und lösen echte Anspannung oft schon innerhalb eines Tages.",
    dreamTip: "Ein Albtraum heute Nacht ist am besten so zu verstehen, dass dein Geist etwas ausräumt — nicht als schlechtes Zeichen.",
    sourceUrl: "https://om-journal.com/moonday/16"
  },
  {
    lunarDay: 17,
    symbol: "Shakti",
    emoji: "⚡",
    tagline: "Liebe und Festfreude triumphieren.",
    overview: "Ein Tag erblühender weiblicher Energie, voller Freude und innerer Freiheit. Günstig für Liebe, Ehebeziehungen oder das Verkuppeln allgemein. Die Überlieferung nennt diesen Tag zudem als ungünstigen Zeitpunkt für Medikamente oder Alkohol, da ihre Wirkung heute ungewöhnlich stark ausfallen soll.",
    stones: "Klarer Amethyst, Rabenauge, Falkenauge, Zirkon.",
    meditation: "Lach- und Tanzmeditation — beginne den Tag mit Lachen, noch bevor du die Augen öffnest, und lass freudvolle Bewegung den Tag durchziehen.",
    relationships: "Dieser Tag ist günstig für Hochzeitsfeiern und Jubiläen, idealerweise gefolgt von einer Hochzeitsreise direkt im Anschluss an die Feier. Die weibliche Energie ist hoch, was Tanzen, Nähe und Verbindung mit dem Partner besonders begünstigt.",
    business: "Die erste Tageshälfte eignet sich gut für Kommunikation, Präsentationen, Teamarbeit und Finanzgeschäfte — nutze sie. Die zweite Hälfte spricht eher für Ruhe als für wichtige Entscheidungen.",
    housework: "Kein Tag für schwere oder anstrengende Aufgaben — lass die Hausarbeit los und wende dich lieber der Feststimmung zu, mit Familienessen, Spielen oder einem Filmabend. Gartenarbeit, besonders die Ernte oder die Weinherstellung, profitiert von der fruchtbaren Energie des Tages.",
    activeOrgans: ["Fortpflanzungsorgane", "Sakralzentrum", "Hormonsystem"],
    doToday: ["Kreative Projekte", "Ausdrucksstarke Bewegung oder Tanz", "Vitalität kultivieren"],
    avoidToday: ["Kreative Energie unterdrücken", "Niedergeschlagene Gedanken", "Übermäßige Einschränkung"],
    foodNote: "Energiespendende, wärmende Speisen. Ingwer, Zimt und natürliche Gewürze tun gut.",
    foodFavor: ["Ingwer", "Zimt", "Wärmende Gewürze"],
    foodAvoid: [],
    dreamFocus: "Kreative Lebenskraft",
    dreamGuidance: "Träume spiegeln sexuelle und kreative Energie wider. Angenehme Träume deuten auf freien Fluss hin, unangenehme fragen, wo Lebenskraft unterdrückt wurde.",
    dreamTiming: "Ein Traum heute Nacht kann sich innerhalb von etwa drei Tagen im wachen Leben zeigen.",
    dreamTip: "Angenehme Bilder deuten darauf hin, dass deine kreative und körperliche Energie gut fließt; beunruhigende zeigen, wo sie gerade zurückgehalten wird.",
    sourceUrl: "https://om-journal.com/moonday/17"
  },
  {
    lunarDay: 18,
    symbol: "Spiegel",
    emoji: "🪞",
    tagline: "Das Äußere spiegelt das Innere.",
    overview: "Alles, was uns heute widerfährt, ist ein Spiegel unseres wahren Selbst. Es lohnt sich, in dich hineinzuschauen und die Gründe für dein Handeln und deine Ansichten zu ergründen.",
    stones: "Weißer Achat, Opal, lila Amethyst, Spinell.",
    meditation: "Spiegelmeditation — betrachte die Menschen um dich herum als Spiegel deiner selbst und visualisiere anschließend dein Idealbild, erfüllt von Licht.",
    relationships: "Am besten heute weder eine Familie gründen noch eine Hochzeitszeremonie abhalten. Erwäge, ein romantisches Treffen abzusagen, oder sei bereit, von deinem Partner etwas Entlarvendes über dich selbst zu hören.",
    business: "Passt zu ruhiger, detailorientierter Arbeit und einfachen Finanzaufgaben — bleib diplomatisch, falls Konflikte aufkommen, und beobachte genau, wer wirklich produktiv ist und wer nur beschäftigt wirkt. Vermeide es, komplexe Projekte zu überstürzen oder dich von anderen zu Entscheidungen drängen zu lassen.",
    housework: "Deine Umgebung spiegelt heute deinen inneren Zustand — plane also sorgfältig, bevor du beginnst, und bevorzuge kleines Aufräumen gegenüber großen Projekten. Das Reinigen deines äußeren Raums räumt tatsächlich auch inneres Durcheinander auf, und Fenster und Glas lassen sich jetzt besonders leicht putzen.",
    activeOrgans: ["Magen", "Darm", "Verdauungsfeuer"],
    doToday: ["Selbstreflexion und Tagebuchschreiben", "Ehrliche innere Bestandsaufnahme", "Bei dem verweilen, was du siehst"],
    avoidToday: ["Eitelkeit oder Selbsttäuschung", "Übermäßige Bildschirmzeit", "Unangenehme Wahrheiten ignorieren"],
    foodNote: "Leicht verdauliche Speisen. Vermeide übermäßiges Essen; probiotische Speisen wie Joghurt unterstützen eine klare Verdauung.",
    foodFavor: ["Leicht verdauliche Speisen", "Probiotische Speisen (Joghurt)"],
    foodAvoid: ["Übermäßiges Essen"],
    dreamFocus: "Selbstreflexion",
    dreamGuidance: "Träume spiegeln die Kluft zwischen dem, wer du gerade bist, und dem, wer du werden willst. Sie können auch Blockaden, Gesundheitshinweise oder praktische Chancen zeigen.",
    dreamTiming: "Träume heute Nacht lohnt es sich aufzuschreiben und später mit dem tatsächlichen Verlauf deines Tages zu vergleichen.",
    dreamTip: "Die Lücke zwischen Traum und Wirklichkeit ist oft die eigentliche Botschaft — ein guter Traum deutet meist auf ein tatsächlich gutes Ergebnis hin.",
    sourceUrl: "https://om-journal.com/moonday/18"
  },
  {
    lunarDay: 19,
    symbol: "Spinne",
    emoji: "🕷️",
    tagline: "Reinigung von Seele und Gewissen — fremde Gedanken müssen weichen.",
    overview: "Die Spinne webt ihr Netz — sei vorsichtig mit neuen Ideen. Begleiche heute keine Schulden, leih dir nichts und geh keine Verträge ein; reinigende Feuerrituale sind empfehlenswert. Meide auch angetrunkene Gesellschaft — ältere Überlieferungen nennen diesen Tag als einen mit ungewöhnlich hohem Risiko dafür.",
    stones: "Labradorit, Morion, Blutstein, Chrysolith, grüner Granit.",
    meditation: "Reinigungsmeditation — reinige deinen Wohnraum und deinen Körper mit Wasser, Räucherwerk oder einer Kerze, begleitet von einer Affirmation des Loslassens.",
    relationships: "Weder das Gründen einer Familie noch eine Hochzeitszeremonie sind heute günstig, ebenso wenig eine Scheidung. Für ein romantisches Treffen ist dies ein ungünstiger Zeitpunkt, mit hoher Wahrscheinlichkeit für ernsthaften Streit.",
    business: "Wähle deine Worte heute mit Bedacht, denn Konflikte entzünden sich leicht — überprüfe Informationen, bespreche Situationen ruhig, und wenn eine Kündigung schon geplant war, ist heute der Tag dafür. Halte die zweite Tageshälfte ruhig und vermeide Verträge, neue Vorschläge oder finanzielle Verpflichtungen.",
    housework: "Ein guter Tag für gründliches Frühjahrsputz-artiges Reinigen und das Ausmisten vernachlässigter Ecken — eine brennende Kerze unterstützt die reinigende Energie. Teile dir die Kräfte gut ein und ruh dich aus, wenn du müde wirst, und lass auch Raum für kreative Projekte im Haus.",
    activeOrgans: ["Lymphsystem", "Milz", "Blut", "Immunsystem"],
    doToday: ["Sanfte spirituelle Praxis", "Gebet oder Ritual", "Um Unterstützung von außen bitten"],
    avoidToday: ["Komplexe Entscheidungen", "Neue Projekte beginnen", "Reisen oder große Umzüge"],
    foodNote: "Einfache, reinigende Speisen. Sehr leichte Mahlzeiten oder Fasten tun gut. Verzichte auf schwere oder verarbeitete Lebensmittel.",
    foodFavor: ["Einfache, reinigende Speisen", "Leichte Mahlzeiten", "Fasten"],
    foodAvoid: ["Schwere Lebensmittel", "Verarbeitete Lebensmittel"],
    dreamFocus: "Tiefe der Psyche",
    dreamGuidance: "Träume können schwierig sein und sollten nicht zu wörtlich gedeutet werden. Nutze Gebet, Loslassen oder Unterstützung von außen, wenn die Bilder sich schwer anfühlen.",
    dreamTiming: "Eine schwierige Nacht für Träume — nimm die Bilder besser nicht zu wörtlich.",
    dreamTip: "Taucht etwas Beunruhigendes auf, hilft ein ruhiger Moment des Loslassens mehr, als es allein entschlüsseln zu wollen.",
    dreamRemedy: "Bei einem wirklich schweren Traum lohnt es sich, mit jemandem darüber zu sprechen, statt allein damit zu sitzen.",
    sourceUrl: "https://om-journal.com/moonday/19"
  },
  {
    lunarDay: 20,
    symbol: "Adler",
    emoji: "🦅",
    tagline: "Verwirf alle Zweifel, nimm deine Wandlung an.",
    overview: "Ein Tag der Offenbarungen, Enthüllungen, spiritueller Wandlung und der Überwindung von Zweifeln. Innere Wandlung ist heute möglich, und der Tag begünstigt das Loslassen von Schulden und belastenden Zuständen.",
    stones: "Roter Jaspis, Jaspis.",
    meditation: "Begegnung mit dem inneren Lehrer — eine geführte Visualisierung, bei der du dich über die Erde erhebst, um Weisheit von deinem höheren Selbst zu empfangen.",
    relationships: "Ein günstiger Tag für eine Hochzeitsfeier; am zwanzigsten Mondtag gegründete Familien werden selten von Eifersucht, Verrat oder Geldsorgen erschüttert. Ein guter Tag für ein ruhiges, friedliches romantisches Treffen.",
    business: "Ein geselliger, offener Tag, der sich gut für Teamarbeit, Finanzangelegenheiten, das Anpacken schwieriger Probleme und den Start neuer Bauvorhaben oder Unternehmungen eignet. Vermeide Passivität oder zu frühes Aufgeben.",
    housework: "Bewahre gegenüber der Familie deine Fassung und dräng heute niemanden zur Hausarbeit — überdenke lieber, wie dein Zuhause organisiert ist, statt neue Aufgaben zu erzwingen. Die Energie des Tages begünstigt neue Bauprojekte, doch Überanstrengung solltest du vermeiden.",
    activeOrgans: ["Augen", "Leber", "Sehzentren", "Gehirn"],
    doToday: ["Absichtsvoll träumen", "Klare Ziele setzen", "Strategisch planen"],
    avoidToday: ["Zerstreute Aufmerksamkeit", "Der Wahrheit ausweichen", "Wichtige Dinge aufschieben"],
    foodNote: "Leberstärkende Speisen: Artischocke, Löwenzahnblätter, frische Gemüsesäfte. Verzichte auf Alkohol.",
    foodFavor: ["Artischocke", "Löwenzahnblätter", "Frische Gemüsesäfte"],
    foodAvoid: ["Alkohol"],
    dreamFocus: "Erbetene Antworten",
    dreamGuidance: "Träume können sich schnell erfüllen und lassen sich gezielt herbeiwünschen. Bitte vor dem Einschlafen um eine Lösung, einen Ort oder eine Reise in die feinstoffliche Welt.",
    dreamTiming: "Träume heute Nacht können sich schnell erfüllen.",
    dreamTip: "Eine gute Nacht, um wirklich um etwas zu bitten — eine Lösung, einen Weg durch ein Problem oder einfach nur Klarheit.",
    sourceUrl: "https://om-journal.com/moonday/20"
  },
  {
    lunarDay: 21,
    symbol: "Pferdeherde",
    emoji: "🐎",
    tagline: "Ein Tag der Gerechtigkeit, des Zusammenhalts und des Vorwärtsschreitens.",
    overview: "Ein Tag von Mut und beharrlichem Vorwärtsschreiten, geprägt von aktiver, kreativer Energie. Ein guter Tag für Gruppenaktivitäten, Abschlüsse oder den Aufbruch zu einer Reise.",
    stones: "Pyrit, Zirkon, Aventurin, Obsidian.",
    meditation: "Pranayama und Atemarbeit — begünstigt Rebirthing-Sitzungen und kräftige Atemübungen zusammen mit körperlicher Bewegung.",
    relationships: "Der einundzwanzigste Mondtag ist günstig für eine Hochzeitsfeier, die fröhlich und groß ausfallen sollte. Ein guter Tag für ein romantisches Treffen — Alleinsein zu vermeiden hilft, trübe Stimmung fernzuhalten.",
    business: "Die Arbeit läuft heute gut, besonders bei Finanzangelegenheiten und allem, was Tempo und Aktivität verlangt — such das Gespräch mit der Führungsebene und erwäge neue Vorhaben. Vermeide es, mit deinem Team aneinanderzugeraten oder dich in Kleinigkeiten zu verlieren.",
    housework: "Ambitionierte Hausprojekte gelingen heute leichter als sonst — Streichen, Tapezieren, Möbelrücken, Wäschewaschen — dank des energiegeladenen Schwungs des Tages. Lenk die zusätzliche Begeisterung in konstruktive Projekte statt in Streit über die Veränderungen.",
    activeOrgans: ["Hüften", "Oberschenkel", "Leber", "Bewegungsapparat"],
    doToday: ["Körperliche Bewegung und Training", "Kreative Kraft ausdrücken", "Mutige Schritte wagen"],
    avoidToday: ["Stillstand", "Ideen zurückhalten", "Passives Abwarten"],
    foodNote: "Energiespendende, proteinreiche Speisen. Körperliche Vitalität steht heute im Mittelpunkt — iss, um Bewegung zu befeuern.",
    foodFavor: ["Energiespendende Speisen", "Proteinreiche Speisen"],
    foodAvoid: [],
    dreamFocus: "Kreative Kraft",
    dreamGuidance: "Träume zeigen vor allem, ob kreative Energie fließt oder blockiert ist. Darüber hinaus sind sie meist weniger bedeutsam und selten vorhersagend.",
    dreamTiming: "Träume heute Nacht gehen selten wörtlich in Erfüllung.",
    dreamTip: "Lies diesen Traum eher als Anzeiger deiner momentanen kreativen Energie denn als Vorhersage dessen, was kommt.",
    sourceUrl: "https://om-journal.com/moonday/21"
  },
  {
    lunarDay: 22,
    symbol: "Ganesha",
    emoji: "🐘",
    tagline: "Ein Tag der Weisheit und des Wissens.",
    overview: "Lernen, Forschen oder jede Arbeit mit Informationen ist heute günstig. Wer sich dem Studium widmet, kann an diesem Tag Fortschritte machen, die sonst Jahre harter Arbeit bräuchten.",
    stones: "Blauer Achat, blauer Saphir, blauer Jaspis, blauer Nephrit, Bernstein.",
    meditation: "Konzentrationsübung — vertiefe dich in ein Thema, ein Symbol oder einen Text, den du besser verstehen möchtest.",
    relationships: "Heute eine Familie zu gründen ist nicht günstig, wohl aber ist es ein hervorragender Zeitpunkt, um eine Silber- oder Goldene Hochzeit zu feiern. Jede Begegnung heute kann etwas Neues und Bedeutsames über Liebe oder einen Partner offenbaren.",
    business: "Begünstigt Bildung und Selbstverbesserung mehr als Geschäfte — studiere, sichte Dokumente und Archive, unterschreibe Verträge und teile dein Wissen. Verzichte darauf, große ernsthafte Vorhaben zu starten oder dich zu überarbeiten, und lass dich nicht von Trägheit einholen.",
    housework: "Am besten für das Ordnen von Arbeitsplatz und Bibliothek geeignet, weniger für allgemeines Putzen — sortiere Bücher und Notizen, richte eine Leseecke ein oder bring neuen Lesestoff nach Hause. Auch ein passender Tag zum Backen und um das Feng-Shui oder Vastu-Layout deines Zuhauses zu planen.",
    activeOrgans: ["Leber", "Dickdarm", "Entgiftungswege"],
    doToday: ["Lernen und Studieren", "Rituale oder Zeremonien beginnen", "Probleme lösen"],
    avoidToday: ["Trägheit", "Bewährte Praktiken auslassen", "Aufschieben"],
    foodNote: "Reinigende Speisen: Gemüse, Getreide, Hülsenfrüchte. Eine sanfte Entgiftung wird heute unterstützt.",
    foodFavor: ["Gemüse", "Getreide", "Hülsenfrüchte"],
    foodAvoid: ["Verarbeitete Lebensmittel"],
    dreamFocus: "Wissen",
    dreamGuidance: "Träume können leer bleiben oder Wissen und Lösungen bringen. Stell vor dem Schlafen eine Frage und schreib auf, was sich zeigt.",
    dreamTiming: "Träume heute Nacht reichen von belanglos bis wirklich aufschlussreich.",
    dreamTip: "Setzt du vor dem Schlafen eine Absicht, achte beim Aufwachen genau hin — diese Nacht kann dir eine echte Antwort schenken.",
    sourceUrl: "https://om-journal.com/moonday/22"
  },
  {
    lunarDay: 23,
    symbol: "Krokodil",
    emoji: "🐊",
    tagline: "Ein Tag der Provokation und der Versuchungen.",
    overview: "Ein Tag der Umkehr, der Vergebung und des Fastens. Hausputz, Aufräumen und Frömmigkeit sind empfehlenswert, Kontakte meidest du besser.",
    stones: "Rauchtopas, schwarzer Nephrit.",
    meditation: "Meditation zur Reinigung des Zuhauses — reinige deinen Raum mit Räucherwerk oder Weihwasser, während du dir vorstellst, wie Sonnenlicht den Raum erfüllt.",
    relationships: "Der dreiundzwanzigste Mondtag ist ungünstig, um eine Familie zu gründen, und Scheidungen verlaufen jetzt schnell und schmerzlos. Ist eine Beziehung angespannt, meide den Kontakt und beherrsche negative Reaktionen, statt heute Frieden schließen zu wollen.",
    business: "Die Energie ist heute kompliziert und konfliktanfällig, besonders später am Tag — allein statt in Gesellschaft zu arbeiten hilft sogar aufwendigen Plänen zum Erfolg. Halte dich an einfache Angelegenheiten, sprich klar und sparsam, und meide Menschenmengen und neue Bekanntschaften. Angefangenes fertigzustellen bringt heute besondere Anerkennung, während der Start von Neuem lieber vermieden wird.",
    housework: "Ruhig, aber knifflig — Putzen, Wäsche und kleine Reparaturen gehen langsamer als sonst, greif also neben der praktischen Arbeit auch auf rituelle Reinigung oder Feng-Shui-Anpassungen zurück. Meide heute Einkäufe und volle Orte.",
    activeOrgans: ["Nieren", "Harnröhre", "Wasserhaushalt"],
    doToday: ["Anpassen und neu überdenken", "Annahmen hinterfragen", "Pläne mit frischem Blick prüfen"],
    avoidToday: ["Dinge für bare Münze nehmen", "Vorschnelle Schlüsse", "Riskante Vorhaben"],
    foodNote: "Feuchtigkeitsspendende, nierenstärkende Speisen. Reduziere heute Salz und verarbeitete Lebensmittel.",
    foodFavor: ["Feuchtigkeitsspendende Speisen", "Nierenstärkende Speisen"],
    foodAvoid: ["Salz", "Verarbeitete Lebensmittel"],
    dreamFocus: "Widerspruch",
    dreamGuidance: "Träume können heute täuschend oder verkehrt sein. Geh vorsichtig mit klaren Schlussfolgerungen um; die gegenteilige Bedeutung liegt oft näher an der Wahrheit.",
    dreamTiming: "Träume heute Nacht laufen oft rückwärts zu dem, was sie zu sagen scheinen.",
    dreamTip: "Ein alarmierend wirkender Traum weist meist eher auf einen inneren Konflikt hin als auf eine reale Bedrohung — versuch, ihn umgekehrt zu lesen.",
    sourceUrl: "https://om-journal.com/moonday/23"
  },
  {
    lunarDay: 24,
    symbol: "Shiva",
    emoji: "🙏",
    tagline: "Erst wenn das Alte zerstört ist, entsteht das Neue.",
    overview: "Ein Tag der Erneuerung männlicher Energie. Die Kraft der Natur ist heute besonders aktiv, und die körperliche Stärke nimmt spürbar zu. Dieser Schub kann in Rivalität oder Reibung umschlagen, wenn du ihn nicht bewusst lenkst.",
    stones: "Schwarzer Jaspis, Schneeflocken-Obsidian, Malachit, blauer Nephrit, Grossular-Granat.",
    meditation: "Tantra- und Erdverbindungspraxis — arbeite mit Mineralien, Yoga oder der Natur, um männliche, schöpferische Energie zu erden.",
    relationships: "Der beste Tag, um für Paare, die sich viele Kinder wünschen, eine Familie zu gründen. Männliche Energie und sexuelle Kraft sind stark, was ein romantisches Treffen besonders wirkungsvoll macht.",
    business: "Ein produktiver Tag für Finanzübersicht, Planung und sogar neue Vorhaben — halte eine Monatsbilanz, sieh dir an, was funktioniert, und bitte um die Anerkennung oder Beförderung, die du dir verdient hast. Auch ein guter Zeitpunkt für Veranstaltungen, Präsentationen und den Abschluss wichtiger Arbeiten.",
    housework: "Die körperliche Kraft ist heute hoch — ein ausgezeichneter Tag für anspruchsvolle Hausprojekte wie Bauen, Reparaturen, Fundamente legen, Pflanzen oder sogar das Streichen eines Zauns. Bitte die Familie um Hilfe, statt sie einzufordern, und bewahre eine harmonische Stimmung.",
    activeOrgans: ["Herz", "Fortpflanzungszentrum", "Lebensenergie (Prana)"],
    doToday: ["Andacht oder spirituelle Praxis", "Tiefe kreative Arbeit", "Wandlungsrituale"],
    avoidToday: ["Lebensenergie verschwenden", "Belanglose Ablenkungen", "Egogetriebenes Handeln"],
    foodNote: "Sattvische, reine Speisen. Verzichte auf alle berauschenden Mittel. Ein heiliger Tag für bewusste Ernährung.",
    foodFavor: ["Sattvische Speisen", "Reine Speisen"],
    foodAvoid: ["Berauschende Mittel"],
    dreamFocus: "Innere Stärke",
    dreamGuidance: "Träume zeigen kreative Kraft, sexuelle Energie und dein Gesamtpotenzial. Gute Träume deuten auf Stärke hin, schwierige zeigen, wo Energie versickert.",
    dreamTiming: "Träume heute Nacht spiegeln direkt deine kreative und körperliche Energie.",
    dreamTip: "Ein beunruhigender Traum signalisiert meist erschöpfte Energie oder etwas Ungelöstes, das echte Erholung braucht, kein weiteres Antreiben.",
    sourceUrl: "https://om-journal.com/moonday/24"
  },
  {
    lunarDay: 25,
    symbol: "Schildkröte",
    emoji: "🐢",
    tagline: "Lausche in der Stille auf die Stimme deiner Seele.",
    overview: "Ein passiver, meditativer Tag — eine Zeit erhöhter Sensibilität, Konzentration und Vorstellungskraft. Höre aufmerksam auf deine innere Stimme, ohne dich zu hetzen.",
    stones: "Spat, Tigerauge, Falkenauge, Katzenauge, rosa Marmor.",
    meditation: "Schutzengel-Meditation — lade vor dem Einschlafen zu einem Dialog mit deinem Schutzengel oder höheren Mächten ein, um deine Lebensaufgabe klarer zu erkennen.",
    relationships: "Besser heute keine Familie gründen, auch wenn Scheidungsverfahren jetzt schnell und schmerzlos verlaufen. Ein romantisches Treffen gelingt, wenn auch ohne großen Gefühlsaufschwung — dieser Tag eignet sich besser dazu, allein über deine Beziehungen nachzudenken.",
    business: "Die erste Tageshälfte begünstigt Untätigkeit — erzwinge weder Teamarbeit noch große Entscheidungen —, doch die zweite Hälfte öffnet sich für das Lösen von Problemen, das Vertrauen auf dein Bauchgefühl bei Geld und ruhigen Alleingang im Handel. Heb dir Verträge und neue Kontakte für einen anderen Tag auf.",
    housework: "Kein Tag für viel Aufhebens — verzichte auf neue Projekte, beschränke dich auf Leichtes und heb dir den Rest für stille Reflexion auf. Fülle dein Zuhause mit Räucherwerk, sanfter Musik oder Handarbeit und bewege dich achtsam durch deinen Raum.",
    activeOrgans: ["Nervensystem", "Gehirn", "Sinnesorgane"],
    doToday: ["Langsame, kontemplative Arbeit", "Naturspaziergänge und Stille", "Intuitives Lesen oder Wahrsagen"],
    avoidToday: ["Hetze", "Reizüberflutung", "Raue oder laute Umgebungen"],
    foodNote: "Nahrhafte, nervenberuhigende Speisen. Warme Suppen, Kräutertees und milde Proteine tun gut.",
    foodFavor: ["Warme Suppen", "Kräutertees", "Milde Proteine"],
    foodAvoid: [],
    dreamFocus: "Intuitive Prophezeiung",
    dreamGuidance: "Träume gelten heute traditionell als prophetisch, doch Intuition zählt mehr als wörtliche Deutung. Reinige und lass Albträume am Morgen los.",
    dreamTiming: "Gilt als eine der wirklich prophetischsten Nächte des Monats.",
    dreamTip: "Vertrau deinem Bauchgefühl zum Traum mehr als einer wörtlichen, Symbol-für-Symbol-Deutung.",
    dreamRemedy: "Bei einem Albtraum ist ein ruhiger Moment der Besinnung und das Waschen des Gesichts mit kühlem Wasser der traditionelle Weg, klar in den Tag zu starten.",
    sourceUrl: "https://om-journal.com/moonday/25"
  },
  {
    lunarDay: 26,
    symbol: "Sumpf",
    emoji: "🌿",
    tagline: "Keine Weisheit gleicht der Stille. Der Tag von Ekadashi (der elfte Tag nach Vollmond).",
    overview: "Vergebliche Mühe ist heute möglich, und leeres Gerede verschwendet Energie. Verzichte auf intensive Aktivität — entspann dich lieber und wähle deine Kontakte mit Bedacht. Auch die wahren Absichten der Menschen kommen jetzt eher ans Licht, achte also darauf, was deine Begegnungen offenbaren.",
    stones: "Gelber Nephrit, Jadeit, Chrysopras.",
    meditation: "Stille Beobachtung — übe Vipassana oder einfaches Atembeobachten im Alleinsein; ein passender Tag, um den inneren Lehrer zu kontaktieren.",
    relationships: "Ein ungünstiger Tag, um eine Familie zu gründen, aber ein geeigneter Zeitpunkt für eine Scheidung, falls nötig. Meide den Kontakt zu neuen Menschen, unterstütze aber einen Partner in einer bereits stabilen Beziehung weiterhin.",
    business: "Am besten bleibst du bei der gewohnten Routine — erledige deine reguläre Arbeit, nimm dir den Rat von Freunden zu Herzen und vermeide es, Neues zu starten, große Entscheidungen zu treffen oder zu reisen. Bleib gelassen und besonnen, besonders am Steuer.",
    housework: "Schone deine Energie, statt dich durch Müdigkeit zu quälen — arbeite nur so viel, wie sich stimmig anfühlt, und mach dir großzügig Pausen. Wende deine Aufmerksamkeit stattdessen nach innen und nutze stille Momente, um zu dir selbst zurückzufinden.",
    activeOrgans: ["Fortpflanzungssystem", "Rückenmarksflüssigkeit", "Immunsystem"],
    doToday: ["Ehrliche Selbstreflexion", "Schlechte Angewohnheiten loslassen", "In der Natur erden"],
    avoidToday: ["Stolz oder Selbsttäuschung", "Toxische Umgebungen", "Klatsch und Eitelkeit"],
    foodNote: "Erdende, reinigende Speisen. Verzichte heute auf fermentierte oder berauschende Speisen.",
    foodFavor: ["Erdende Speisen", "Reinigende Speisen"],
    foodAvoid: ["Fermentierte Speisen", "Berauschende Mittel"],
    dreamFocus: "Gewohnheiten und Stolz",
    dreamGuidance: "Träume können Gewohnheiten, Laster, Stolz oder ein verzerrtes Selbstwertgefühl offenbaren. Farbenfrohe Träume können die Stimmung heben und sich erfüllen.",
    dreamTiming: "Träume heute Nacht decken eher Gewohnheiten auf, als Ereignisse vorherzusagen.",
    dreamTip: "Welche Schwäche oder schlechte Angewohnheit auch auftaucht, lohnt sich ein zweiter Blick — heute Nacht ist selten etwas davon zufällig.",
    sourceUrl: "https://om-journal.com/moonday/26"
  },
  {
    lunarDay: 27,
    symbol: "Dreizack",
    emoji: "🔱",
    tagline: "Ein klarer Geist öffnet den Weg zu verborgenem Wissen.",
    overview: "Die Herausforderung, die den Menschen heute gestellt wird, ist, sich selbst zu finden und das Entdeckte mit anderen zu teilen. Ein guter Tag für Meditation, mit intuitiver Einsicht und verborgenem Wissen in Reichweite.",
    stones: "Lila Amethyst, Smaragd, Adular, rosa und karminroter Quarz, Selenit.",
    meditation: "Heilige Musik und Gebet — singe Mantras oder bete für andere, um heute einen intuitiven Kanal der Einsicht zu öffnen.",
    relationships: "Ein guter Zeitpunkt, um eine Familie zu gründen, wobei die Hochzeitszeremonie für mehr Stabilität ruhig und still gehalten werden sollte, mit Meeres- oder Schiffsmotiven in der Dekoration. Ein günstiger Tag für romantische Treffen und für Versöhnung nach Streit.",
    business: "Gute Nachrichten oder Einsichten können von Freunden kommen, und der Tag begünstigt das Begleichen von Schulden, wohltätiges Geben, das Unterschreiben von Verträgen, Recherche und die Planung des kommenden Monats. Vermeide es, neue Vorhaben zu starten oder mit deinen Erfolgen zu prahlen.",
    housework: "Besser geeignet für innere, spirituelle Arbeit als für schwere Hausarbeit, wobei leichte Aufgaben in Ordnung sind, solange sie keine Unruhe auslösen. Kaufe nur mit klarer Absicht ein und nutze den Tag, um deinen Wohnraum zu verstehen, statt ihn nur zu putzen.",
    activeOrgans: ["Schienbeine", "Knöchel", "Hormonsystem"],
    doToday: ["Meditation und spirituelles Studium", "Intuition entwickeln", "Klare innere Arbeit"],
    avoidToday: ["Alkohol und Rauschmittel", "Übermaß oder Genusssucht", "Oberflächliche oder ablenkende Beschäftigungen"],
    foodNote: "Gewürzte, wärmende Mahlzeiten. Kardamom, Kurkuma, Nelke und Pfeffer sind günstig. Verzichte auf Kartoffeln, Zitrusfrüchte und Alkohol.",
    foodFavor: ["Kardamom", "Kurkuma", "Nelke und Pfeffer"],
    foodAvoid: ["Kartoffeln", "Zitrusfrüchte", "Alkohol"],
    dreamFocus: "Wahres Wesen",
    dreamGuidance: "Träume und Vorzeichen können intuitives Wissen tragen und das wahre Wesen von Menschen oder Situationen offenbaren. Deute sie behutsam — Irrtümer passieren heute leicht.",
    dreamTiming: "Träume und Vorzeichen können sich heute Nacht tatsächlich erfüllen.",
    dreamTip: "Du bekommst vielleicht echte intuitive Einsicht über eine Person oder Situation — doch es ist auch leicht, das Signal misszudeuten, halte deine Interpretation also mit Vorsicht.",
    sourceUrl: "https://om-journal.com/moonday/27"
  },
  {
    lunarDay: 28,
    symbol: "Lotus",
    emoji: "🪷",
    tagline: "Ein ruhiger, günstiger Tag.",
    overview: "Diesen Tag solltest du aktiv und mit guter Laune erleben. Neue Projekte lassen sich beginnen, und der Tag ist besonders günstig für den Kauf von Grundstücken oder Immobilien.",
    stones: "Chrysopras, Milchopal, Jade, Aquamarin, Amethyst.",
    meditation: "Chakra- und Klartraum-Meditation — begünstigt das Reinigen der Chakren und Übungen zur Traumklarheit, etwa das Betrachten deiner Hände vor dem Einschlafen.",
    relationships: "An diesem Tag ist es günstig, für ältere, erfahrene Partner eine Familie zu gründen. Ein geeigneter Tag für ruhige Treffen, bei denen ihr die Chance habt, neue Gefühle und Charakterzüge aneinander zu entdecken.",
    business: "Ein günstiger Tag mit spirituellem Unterton — gut, um neue Projekte zu starten, Finanzen zu regeln und wichtige Dokumente zu unterschreiben. Bleib bei der Arbeit gelassen und vermeide Überarbeitung.",
    housework: "Neigt eher zur Verschönerung des Zuhauses als zum Großputz — häng Tapeten, neue Vorhänge auf, stell Blumentöpfe auf oder dekoriere einfach und genieße das Ergebnis. Miste aus, was du nicht mehr willst, vermeide aber alles Zerstörerische.",
    activeOrgans: ["Blut", "Herz-Kreislauf-System", "Herzzentrum"],
    doToday: ["Liebesrituale und Herzöffnung", "Anderen dienen", "Dankbarkeit ausdrücken"],
    avoidToday: ["Verbitterung oder Groll", "Gefühlsfluss blockieren", "Isolation"],
    foodNote: "Herzstärkende, milde Speisen. Ausreichend zu trinken ist besonders wichtig. Iss mit Liebe und Aufmerksamkeit.",
    foodFavor: ["Herzstärkende Speisen", "Milde Speisen", "Ausreichend Flüssigkeit"],
    foodAvoid: [],
    dreamFocus: "Hindernisse und Liebe",
    dreamGuidance: "Träume können Hindernisse, Lösungen, Hinweise auf die Zukunft und das gefühlvolle Feld der Liebe zeigen. Verstehe sie als Mitteilungen, die durch deine eigenen Entscheidungen geformt sind.",
    dreamTiming: "Träume heute Nacht können prophetisch sein, besonders was Beziehungen betrifft.",
    dreamTip: "Im Traum gezeigte Hindernisse bringen oft gleich einen Hinweis mit, wie du sie überwindest; auch alte, vergangen wirkende Bilder verdienen Beachtung.",
    sourceUrl: "https://om-journal.com/moonday/28"
  },
  {
    lunarDay: 29,
    symbol: "Hydra",
    emoji: "🌊",
    tagline: "Reinige dich und dein Zuhause — und bleib rein.",
    overview: "Bleib enthaltsam und bescheiden, übe dich in Demut und Umkehr; heute ist ein guter Tag zum Fasten und Heilen. Beginne nichts Neues, bring aber zu Ende, was du schon angefangen hast. Mehrere Mondtraditionen betrachten diesen Tag als einen der ungünstigsten des Monats — halte deine Erwartungen also bescheiden und lass alles Aufschiebbare warten.",
    stones: "Schwarze Perle, Perlmutt, Obsidian, weißer Opal, Labradorit, bunter Jaspis.",
    meditation: "Reinigungsmeditation — ein kurzes kaltes Fußbad oder eine bis zum Ende heruntergebrannte Kerze hilft, negative Energie loszulassen.",
    relationships: "An diesem Tag ist es ratsam, weder eine Familie zu gründen noch eine Hochzeitsfeier abzuhalten. Auch für eine Scheidung ist er ungünstig, da die Wahrscheinlichkeit für Streit und Skandal hoch ist.",
    business: "Vermeide Konflikte und dränge nicht auf Veränderung — mach lieber Bestandsaufnahme, warte Geräte, räume das Büro auf oder erledige offene Kleinigkeiten allein. Halte dich fern von Finanzgeschäften, Krediten, Verträgen und Neueinstellungen.",
    housework: "Ideal für einen abschließenden Monatsputz — verstehe das Ausmisten des physischen Raums auch als Klärung des Geistes; Kerzen oder ein einfaches Gebet unterstützen die Arbeit. Die Energie des Monats ist jetzt am schwächsten, vermeide also Überanstrengung und heb dir nicht das ganze Putzen für diesen einen Tag auf.",
    activeOrgans: ["Nieren", "Harnwege", "Entgiftungswege"],
    doToday: ["Alte Energie klären und loslassen", "Offene Angelegenheiten abschließen", "Gebet und Vergebung"],
    avoidToday: ["Neue Projekte beginnen", "Konflikte oder Konfrontationen", "Kräftezehrende Umgebungen"],
    foodNote: "Sehr leichte, reinigende Ernährung. Fasten oder minimales Essen unterstützt die klärende Energie dieses Tages.",
    foodFavor: ["Sehr leichte Speisen", "Fasten"],
    foodAvoid: ["Schwere Mahlzeiten"],
    dreamFocus: "Schwierige Klärung",
    dreamGuidance: "Träume können kompliziert oder beängstigend sein, weil unbewusste Negativität sich löst. Halte den Tag harmonisch und such Unterstützung für schweres Traummaterial.",
    dreamTiming: "Träume heute Nacht können kompliziert, unangenehm oder beängstigend ausfallen — meist ist das aufgestaute Anspannung, die an die Oberfläche kommt, kein schlechtes Omen.",
    dreamTip: "Bleibt ein Traum von heute Nacht an dir haften, lohnt es sich, ihn mit jemandem zu besprechen, statt allein damit zu bleiben.",
    dreamRemedy: "Deinen Raum heute Abend vor dem Schlafen mit Kerzenlicht zu klären, kann abmildern, was auftaucht.",
    sourceUrl: "https://om-journal.com/moonday/29"
  },
  {
    lunarDay: 30,
    symbol: "Goldener Schwan",
    emoji: "🕊️",
    tagline: "Zieh Bilanz, nimm dich an und mach den Schritt in den neuen Tag.",
    overview: "Ein besonders harmonischer und leichter Tag, der dem Abschließen von Angelegenheiten oder einer Monatsbilanz gewidmet sein sollte. Begleiche Schulden und lass los, was überflüssig geworden ist. Nicht jeder Mondmonat erreicht einen dreißigsten Tag — tritt er ein, trägt er umso mehr Bedeutung.",
    stones: "Madrepore, Bergkristall, Turmalin.",
    meditation: "Reflektierende Naturmeditation — setz dich nach draußen und lass den vergangenen Monat Revue passieren, mit einer Bestätigung dessen, was du bewahren und was du loslassen willst.",
    relationships: "An diesem Tag ist es ratsam, keine Familie zu gründen, da jetzt geschlossene Verbindungen kurzlebig und wenig tragfähig sein können. Verbring den Tag am besten mit deinem geliebten Partner an einem ruhigen, friedlichen Ort, wenn möglich im Freien.",
    business: "Gut, um Finanzen zu regeln, Schulden zurückzuzahlen und deine Gedanken vor dem Start des neuen Zyklus zu ordnen — ein Spaziergang draußen hilft, für das Kommende neue Kraft zu tanken. Verschiebe den Start von Neuem auf später.",
    housework: "Begünstigt das Fertigstellen von bereits Begonnenem mehr als einen Neustart — behandle den Tag wie einen ruhigen Feiertag, mit Gartenarbeit oder einem Spaziergang barfuß im Freien. Blick mit Dankbarkeit auf den vergangenen Monat zurück, statt bei seinen Schwierigkeiten zu verweilen.",
    activeOrgans: ["Wirbelsäule", "Nervensystem", "Integration des ganzen Körpers"],
    doToday: ["Dankbarkeits- und Abschlussrituale", "Den Mondmonat würdigen und Revue passieren lassen", "Ausruhen und verarbeiten"],
    avoidToday: ["Neue Vorhaben beginnen", "Überanstrengung", "Unachtsames oder überstürztes Handeln"],
    foodNote: "Festliche, aber ausgewogene Mahlzeiten. Würdige den Zyklus mit bewusstem, dankbarem Essen.",
    foodFavor: ["Festliche Mahlzeiten", "Ausgewogene Mahlzeiten"],
    foodAvoid: [],
    dreamFocus: "Abschluss des Zyklus",
    dreamGuidance: "Träume können hell und bedeutsam sein, besonders wenn du bewusst mit dem Monat gearbeitet hast. Halte fest, was sich abschließt und was als Nächstes Aufmerksamkeit braucht.",
    dreamTiming: "Nicht jeder Mondmonat erreicht diesen Tag — ein Traum heute Nacht trägt daher etwas mehr Gewicht.",
    dreamTip: "Helle, einprägsame Träume heute Nacht verdienen es, als echten Abschluss des Monats gewürdigt zu werden, besonders wenn du bewusst mit ihm gearbeitet hast.",
    sourceUrl: "https://om-journal.com/moonday/30"
  }
];
