import type { ZodiacSign } from "./zodiacSource";

export const zodiacSignsDe: ZodiacSign[] = [
  {
    name: "Widder",
    shortName: "Wid",
    symbol: "♈",
    element: "Feuer",
    mode: "Kardinal",
    inPhrase: "im Widder",
    guidance: "Der Mond im Widder läuft heiß und vital — bewege dich, trinke ausreichend, und baue Ruhelosigkeit lieber durch Bewegung ab als durch Gereiztheit. Geh sparsam mit Kaffee, Zucker und Schokolade um.",
    bestFor: ["erste Schritte", "Körperwärme", "Entscheidungen"],
    avoid: ["Ungeduld", "scharfe Worte", "Hektik"],
    relationships: "Anziehung wirkt schnell und magnetisch — besser geeignet für kurze, leidenschaftliche Romanzen als für sorgfältige Bindung. Familienangelegenheiten treten hinter private Interessen zurück.",
    business: "Gut für mutige Schritte und Originalität, weniger für Verträge oder langfristige Planung. Achte auf Impulsivität — unterschreibe nichts, worüber du nicht eine Nacht geschlafen hast.",
    housework: "Schärfe Messer und Scheren, repariere kleine mechanische Dinge und putze Glas und Fenster. Lass Geschirr und feines Porzellan für einen sanfteren Tag.",
    gardening: "Ein Fruchttag mit steigender Energie. Pflanze Nutzpflanzen, ernte Getreide und pfropfe den Obstgarten, solange der Mond zunimmt; schneide und bekämpfe Schädlinge, wenn er abnimmt.",
    activeOrgans: ["Kopf", "Gehirn", "Augen", "Gesicht"],
    foodNote: "Eisenreiches Gemüse und belebende Speisen. Vermeide übermäßige Schärfe oder Koffein, die das System überhitzen.",
    foodFavor: ["Eisenreiches Gemüse", "Belebende Speisen"],
    foodAvoid: ["Übermäßige Schärfe", "Koffein"]
  },
  {
    name: "Stier",
    shortName: "Sti",
    symbol: "♉",
    element: "Erde",
    mode: "Fix",
    inPhrase: "im Stier",
    guidance: "Der Mond im Stier begünstigt neue Projekte und die Stabilisierung deiner Finanzen — ein günstiger Tag für Möbel oder Immobilien. Halte Hals und Ohren warm, wenn es kühler wird.",
    bestFor: ["Behaglichkeit", "Geldangelegenheiten", "sinnliche Erdung"],
    avoid: ["Sturheit", "Bequemlichkeitsfallen", "Unflexibilität"],
    relationships: "Der Stier-Mond begünstigt die Liebe — warm, sinnlich, unaufgeregt. Eine gute Zeit für Ausflüge, kleine Festmahle und Zuneigung, die sich durch Berührung zeigt.",
    business: "Günstig für ernsthafte, beständige Arbeit: Finanzen, Bewerbungen, Grundstücke und Immobilien. Baue auf dem auf, was bereits Gewicht hat.",
    housework: "Stark für schwere, körperliche Arbeiten, die Muskeln und Geduld belohnen. Monotone Aufgaben lassen sich jetzt gut abschließen.",
    gardening: "Eines der fruchtbarsten Zeichen zum Pflanzen. Setze Wurzeln, Bäume und Sträucher, und verpflanze alles, was neuen Boden braucht.",
    activeOrgans: ["Hals", "Nacken", "Schilddrüse", "Stimmbänder", "Ohren"],
    foodNote: "Nahrhafte, erdende Speisen, langsam gegessen. Vermeide übermäßiges Essen; kaue gründlich und genieße die Mahlzeit.",
    foodFavor: ["Nahrhafte, erdende Speisen", "Langsames Essen"],
    foodAvoid: ["Übermäßiges Essen"]
  },
  {
    name: "Zwillinge",
    shortName: "Zwi",
    symbol: "♊",
    element: "Luft",
    mode: "Veränderlich",
    inPhrase: "in den Zwillingen",
    guidance: "Der Mond in den Zwillingen öffnet den Tag für Gespräche — gut, um Menschen zu treffen, Ideen auszutauschen, zu telefonieren und Nachrichten zu schreiben. Dehne Schultern und oberen Rücken.",
    bestFor: ["Nachrichten", "Lernen", "leichte Planung"],
    avoid: ["zerstreute Konzentration", "Ruhelosigkeit", "im Kopf leben"],
    relationships: "Bindungen, die jetzt entstehen, bleiben locker und unverbindlich — besser geeignet, um Menschen kennenzulernen, als um etwas festzulegen. Lass Neugier an die Stelle von Druck treten.",
    business: "Am besten für Networking, das Vorstellen von Ideen und den Austausch von Informationen. Treibe bestehende Projekte voran, statt neue zu starten.",
    housework: "Eine gute Zeit für die Luftqualität — installiere Ventilatoren oder einen Luftreiniger, lüfte Räume und vertreibe verbrauchte Luft.",
    gardening: "Während der Mond abnimmt, säe, pflanze und verpflanze Blumen und Kletterpflanzen. Auch ein passendes Zeitfenster für Schädlingsbekämpfung und Bodenpflege.",
    activeOrgans: ["Schultern", "Arme", "Hände", "Lunge", "Nervensystem"],
    foodNote: "Leichte, abwechslungsreiche Speisen. Atemübungen und lungenstärkende Kräuter tun dieser Stellung gut.",
    foodFavor: ["Leichte, abwechslungsreiche Speisen", "Lungenstärkende Kräuter"],
    foodAvoid: ["Schwere Speisen"]
  },
  {
    name: "Krebs",
    shortName: "Kre",
    symbol: "♋",
    element: "Wasser",
    mode: "Kardinal",
    inPhrase: "im Krebs",
    guidance: "Der Mond im Krebs macht emotional empfindsam — begegne Gefühlen mit Fingerspitzengefühl und sorge für ausreichend Ruhe. Bevorzuge leichte Kost, und es ist ein guter Tag für Kosmetik- oder Zahnpflege.",
    bestFor: ["Pflege des Zuhauses", "Familienversöhnung", "Erinnerungen"],
    avoid: ["Launenhaftigkeit", "Anklammern", "in der Vergangenheit verharren"],
    relationships: "Zärtlichkeit nimmt zu — Menschen werden sentimental, verträumt, leicht gerührt. Wärme vertieft den Kontakt, besonders zu denen, die dir am nächsten stehen.",
    business: "Die Stimmung ist empfindlich und leicht verletzlich, geh also mit Fingerspitzengefühl statt mit Druck vor. Erfasse die Stimmung im Raum, bevor du auf Ergebnisse drängst.",
    housework: "Gut für die feuchten Arbeiten im Haushalt — Staubsaugen, Wischen, das Bad auffrischen. Allgemeine Reinigung gelingt reibungslos.",
    gardening: "Eines der fruchtbarsten Zeichen. Setze feuchtigkeitsliebende, blattreiche Zierpflanzen, und schneide oder pfropfe jetzt den Obstgarten.",
    activeOrgans: ["Magen", "Brust", "Brustkorb", "Lymphsystem"],
    foodNote: "Wohlfühlkost und leicht verdauliche Mahlzeiten. Warme Suppen, Milchprodukte und milde Eintöpfe wirken unterstützend und beruhigend.",
    foodFavor: ["Wohlfühlkost", "Leicht verdauliche Mahlzeiten", "Warme Suppen und Eintöpfe"],
    foodAvoid: ["Schwer verdauliche Speisen"]
  },
  {
    name: "Löwe",
    shortName: "Löw",
    symbol: "♌",
    element: "Feuer",
    mode: "Fix",
    inPhrase: "im Löwen",
    guidance: "Der Mond im Löwen hebt die kreative Begeisterung — bleib aktiv und entschlossen, und sorge für ausreichend Ruhe, um das Herz zu schützen. Ein guter Tag für einen Haarschnitt oder einen festlichen Anlass.",
    bestFor: ["Kreativität", "Romantik", "Selbstvertrauen"],
    avoid: ["Stolz", "Dramatik", "Bestätigung suchen"],
    relationships: "Die romantischste Phase des Monats — Liebe auf den ersten Blick ist durchaus möglich. Lass Wärme und ein bisschen Dramatik ihren Moment haben.",
    business: "Kreative Inspiration ist hoch, ebenso Optimismus, Eloquenz und Selbstvertrauen. Gut für alles, wobei du glänzen darfst.",
    housework: "Bring deine eigene Kunst und Persönlichkeit ins Zuhause ein. Lass etwas unverkennbar Eigenes im Raum erscheinen.",
    gardening: "Eines der unfruchtbarsten Zeichen. Schneide trockene Äste zurück; solange der Mond zunimmt, säe in feuchten Boden oder lege einen neuen Rasen an.",
    activeOrgans: ["Herz", "Wirbelsäule", "Oberer Rücken"],
    foodNote: "Wärmende, großzügige Kost. Herzgesunde Wahl: Beeren, Blattgemüse, Olivenöl.",
    foodFavor: ["Wärmende, großzügige Kost", "Beeren, Blattgemüse, Olivenöl"],
    foodAvoid: ["Herzbelastende, fettige Speisen"]
  },
  {
    name: "Jungfrau",
    shortName: "Jun",
    symbol: "♍",
    element: "Erde",
    mode: "Veränderlich",
    inPhrase: "in der Jungfrau",
    guidance: "Der Mond in der Jungfrau begünstigt geschäftliche und geistige Arbeit — ein guter Tag, um wichtige Projekte zu beginnen. Iss gut, und es ist ein schöner Tag für Haarschnitte, Maniküre und Handpflege.",
    bestFor: ["Routinen", "Gesundheitsnotizen", "Organisieren"],
    avoid: ["Perfektionismus", "Grübeln", "Selbstkritik"],
    relationships: "Verbindungen, die jetzt entstehen, sind eher praktisch als leidenschaftlich, aufgebaut auf Verständnis und Verantwortung statt auf mitreißende Romantik.",
    business: "Ein starker Auftakt für neue Projekte; Effizienz, Pünktlichkeit und rationales Denken fallen leicht. Buchhaltung und detaillierte Finanzarbeit gelingen besonders gut.",
    housework: "Gut für die Grundreinigung der Küche, besonders des Kühlschranks, und für Gerätereparaturen. Lass große Wäscheladungen zum Lüften lieber aus.",
    gardening: "Ein Wurzeltag mit absteigender Energie, das beste Zeichen zum Setzen und Verpflanzen. Reichere den Boden an und bekämpfe Schädlinge, aber verlass dich nicht darauf, dass Eingelagertes lange hält.",
    activeOrgans: ["Darm", "Verdauungssystem", "Bauchspeicheldrüse", "Milz"],
    foodNote: "Saubere, leicht verdauliche Speisen. Fermentierte Lebensmittel und Ballaststoffe unterstützen den Darm. Iss regelmäßig und maßvoll.",
    foodFavor: ["Saubere, leicht verdauliche Speisen", "Fermentierte Lebensmittel und Ballaststoffe", "Regelmäßige, maßvolle Mahlzeiten"],
    foodAvoid: ["Unregelmäßige, schwere Mahlzeiten"]
  },
  {
    name: "Waage",
    shortName: "Waa",
    symbol: "♎",
    element: "Luft",
    mode: "Kardinal",
    inPhrase: "in der Waage",
    guidance: "Der Mond in der Waage begünstigt Gespräche, Verhandlungen und das Vereinbaren von Terminen. Halte Nieren und Blase warm, und es ist ein guter Tag für Gesichtsbehandlungen, Haarschnitte, Augenpflege oder den Zahnarzt.",
    bestFor: ["Gespräche", "Gestaltung", "Vereinbarungen"],
    avoid: ["es allen recht machen wollen", "Konflikten ausweichen", "Unentschlossenheit"],
    relationships: "Harmonie und offenherzige Gespräche fallen leicht, und Partnerschaften finden ihr Gleichgewicht. Lass Höflichkeit nicht echtes Engagement ersetzen, sonst wird es formell statt nah.",
    business: "Gut für Verhandlungen und diplomatische Treffen, nicht für wichtige Entscheidungen. Besser, Laufendes abzuschließen, als Neues zu beginnen.",
    housework: "Setze auf Schönheit und Ausgewogenheit — Fenster (besonders bei abnehmendem Mond), dekorative Details, das Ordnen von Büchern und Zeitschriften. Wäsche trocknet schnell.",
    gardening: "Ein Blütentag mit absteigender Energie. Verpflanze, setze blühende Kräuter, und ernte — jetzt gewonnenes Saatgut ist meist von hoher Qualität.",
    activeOrgans: ["Nieren", "Unterer Rücken", "Nebennieren", "Haut"],
    foodNote: "Basische, ausgewogene Ernährung. Gurke, Wassermelone und Zitronenwasser unterstützen die Nieren.",
    foodFavor: ["Basische, ausgewogene Ernährung", "Gurke, Wassermelone, Zitronenwasser"],
    foodAvoid: ["Säurebildende, unausgewogene Speisen"]
  },
  {
    name: "Skorpion",
    shortName: "Sko",
    symbol: "♏",
    element: "Wasser",
    mode: "Fix",
    inPhrase: "im Skorpion",
    guidance: "Der Mond im Skorpion begünstigt kreative und geistige Arbeit und sogar das Lösen hartnäckiger Probleme — geh nur mit emotionalen Angelegenheiten behutsam um. Halte die Füße warm; ein passabler Tag, um mit Renovierungen zu beginnen.",
    bestFor: ["Schattenarbeit", "Intimität", "Loslassen"],
    avoid: ["Misstrauen", "Kontrolle", "Loyalität auf die Probe stellen"],
    relationships: "Leidenschaft und Flirten intensivieren sich, und Bindungen vertiefen sich — aber auch Eifersucht und Misstrauen können wachsen. Bewahre Vertrauliches und lass Ehrlichkeit die Wandlung bewirken.",
    business: "Eine der emotional aufgeladensten Phasen — halte Abstand zu Autoritätspersonen, aber vertrau der gesteigerten Konzentration bei ernsten, gewichtigen Entscheidungen.",
    housework: "Gut, um alten, unnützen Ballast auszumisten, besonders in den staubigen, vergessenen Ecken. Wäsche und Geschirr gelingen gut; lass Bettwäsche lüften oder feuchte Kleidung einlagern lieber aus.",
    gardening: "Ein Blatttag mit absteigender Energie. Sammle Heilkräuter, pfropfe und mähe, aber warte mit dem Anreichern von Gemüsebeeten oder dem Fällen von Bäumen.",
    activeOrgans: ["Fortpflanzungsorgane", "Dickdarm", "Blase", "Becken"],
    foodNote: "Reinigende, regenerierende Kost. Vermeide Extreme; tiefe, zielgerichtete Ernährung ist begünstigt.",
    foodFavor: ["Reinigende, regenerierende Kost", "Zielgerichtete Ernährung"],
    foodAvoid: ["Extreme"]
  },
  {
    name: "Schütze",
    shortName: "Sch",
    symbol: "♐",
    element: "Feuer",
    mode: "Veränderlich",
    inPhrase: "im Schützen",
    guidance: "Der Mond im Schützen bringt fröhliche Energie — gut für Verträge, Bewerbungen und Reisen. Überlade dich nicht; es ist auch ein schöner Tag für Massagen, Maniküre und andere Pflege.",
    bestFor: ["Reisepläne", "Lehren", "Glaube"],
    avoid: ["Ruhelosigkeit", "Schroffheit", "Details übergehen"],
    relationships: "Eine günstige Phase für romantische Ausflüge, Feiern und gemeinsame Abenteuer. Romantik ist jetzt leidenschaftlich und optimistisch, wenn auch manchmal kurz.",
    business: "Fröhliche Energie und steigende Aktivität begünstigen Verträge, Bewerbungen und rechtliche Angelegenheiten. Gut für den Start von Vorhaben und für Reisen, nicht für den Kauf von Immobilien.",
    housework: "Beende, wofür du motiviert bist. Glas lässt sich leicht reinigen und polieren; eine gute Zeit zum Bügeln, Kleidersortieren, Einkochen und Backen.",
    gardening: "Ein Fruchttag. Setze Obstbäume, säe Getreide und bekämpfe Schädlinge im Boden, aber warte mit neuem Pflanzen oder Umgraben.",
    activeOrgans: ["Hüften", "Oberschenkel", "Leber", "Ischiasnerv"],
    foodNote: "Großzügige, leberstärkende Kost. Bitteres Blattgemüse, rote Bete und Artischocke sind besonders förderlich.",
    foodFavor: ["Leberstärkende Kost", "Bitteres Blattgemüse, rote Bete, Artischocke"],
    foodAvoid: ["Leberbelastende, schwere Speisen"]
  },
  {
    name: "Steinbock",
    shortName: "Ste",
    symbol: "♑",
    element: "Erde",
    mode: "Kardinal",
    inPhrase: "im Steinbock",
    guidance: "Der Mond im Steinbock begünstigt Planung und den Start ernsthafter Projekte sowie Kosmetik- und Augenpflege. Meide heute Behörden.",
    bestFor: ["Prioritäten", "Karriere", "langfristige Pläne"],
    avoid: ["Kälte", "Selbstkritik", "Workaholismus"],
    relationships: "Besser geeignet für stillen, sachlichen Kontakt als für Romantik oder Feiern — sag weniger, und lass Bindung langsam wachsen. Was jetzt beginnt, kann lange und beständig anhalten.",
    business: "Günstig für Planung und den Start ernsthafter Projekte, Arbeit, die Präzision oder das Befolgen von Anweisungen erfordert, sowie Immobilien. Vermeide Kredite, Schulden und Bewerbungen; die Logik ist stark.",
    housework: "Gut für gründliches, unsentimentales Ausmisten — es fällt jetzt leichter, Dinge loszulassen. Lass das Einlagern von Kleidung oder Schuhen lieber aus, und schone dabei deine Knie.",
    gardening: "Ein Wurzeltag mit steigender Energie. Pflanze Wurzelgemüse und Wintergemüse, jäte, komposte und bekämpfe Schädlinge im Boden — sowohl Ernte- als auch Saatgutqualität sind stark.",
    activeOrgans: ["Knie", "Knochen", "Gelenke", "Zähne", "Nägel"],
    foodNote: "Mineralstoffreiche Kost: Knochenbrühe, Blattgemüse, Milchprodukte. Unterstützt die strukturelle Gesundheit und das Skelettsystem.",
    foodFavor: ["Mineralstoffreiche Kost", "Knochenbrühe, Blattgemüse, Milchprodukte"],
    foodAvoid: ["Mineralstoffraubende Speisen"]
  },
  {
    name: "Wassermann",
    shortName: "Was",
    symbol: "♒",
    element: "Luft",
    mode: "Fix",
    inPhrase: "im Wassermann",
    guidance: "Der Mond im Wassermann weckt Neugier auf das Unbekannte, mit Momenten der Inspiration — ein günstiger Tag für Meetings und Konferenzen. Meide Behörden, und kümmere dich um deine Beine.",
    bestFor: ["Gemeinschaft", "Ideen", "Technologie"],
    avoid: ["Distanziertheit", "Starrheit", "Gefühle verleugnen"],
    relationships: "Günstig für Freundschaft und Flirten — lass Originalität und Wärme Menschen anziehen. Bindungen neigen zum Platonischen, wobei Freundschaft die Romantik stärkt.",
    business: "Gut für Meetings und Konferenzen, heikel, wenn es um Vorgesetzte oder Autoritäten geht. Innovation, Forschung und öffentliches Reden blühen auf.",
    housework: "Gut für chemische Reinigung, neue Elektronik, Fensterputzen, Lüften von Räumen und Wäsche, die einen frischen Duft braucht. Backen und kleine Feiern sind ebenfalls begünstigt.",
    gardening: "Eines der unfruchtbarsten Zeichen. Konzentriere dich auf Schädlings- und Krankheitsvorbeugung; verzichte auf Pflanzen oder Verpflanzen, da junge Triebe jetzt kämpfen.",
    activeOrgans: ["Schienbeine", "Fußgelenke", "Kreislaufsystem"],
    foodNote: "Leichte, flüssigkeitsreiche Kost. Ein guter Kreislauf wird durch moderate Bewegung und stetige Flüssigkeitszufuhr unterstützt.",
    foodFavor: ["Leichte, flüssigkeitsreiche Kost", "Stetige Flüssigkeitszufuhr"],
    foodAvoid: ["Entwässernde Speisen und Getränke"]
  },
  {
    name: "Fische",
    shortName: "Fis",
    symbol: "♓",
    element: "Wasser",
    mode: "Veränderlich",
    inPhrase: "in den Fischen",
    guidance: "Der Mond in den Fischen begünstigt Ruhe, Romantik und Kreativität — Saunagänge und Hand- oder Fußbäder passen zur Stimmung. Alkohol, Kaffee und manche Medikamente wirken stärker als sonst, geh heute also sparsamer damit um.",
    bestFor: ["Traumarbeit", "Musik", "Mitgefühl"],
    avoid: ["verschwommene Grenzen", "Realitätsflucht", "die Gefühle anderer aufsaugen"],
    relationships: "Liebe kann sich jetzt größer als das Leben anfühlen — folge deiner Intuition, bleib aber wachsam gegenüber Illusionen, und sei bereit zu gehen, wenn Zweifel bestehen bleiben.",
    business: "Begünstigt kreative Arbeit, die Suche nach Investoren und wohltätige Vorhaben mehr als harte Strategie. Ruhe und Intuition dienen besser als geistige Schwerarbeit; rechtliche Angelegenheiten können erfolgreich verlaufen.",
    housework: "Eine Zeit zum Ausruhen statt zum Ackern. Wasserbezogene Aufgaben wie Wäsche und Wischen passen zur Stimmung; lass Bettwäsche ungelüftet, da Feuchtigkeit haften bleibt.",
    gardening: "Eines der fruchtbarsten Zeichen. Pflanze Blattgemüse, gieße Zimmerpflanzen, mähe den Rasen, aber verzichte auf Rückschnitt oder Einkochen, da die Ernte sich nicht hält.",
    activeOrgans: ["Füße", "Lymphsystem", "Immunsystem"],
    foodNote: "Sanfte, nahrhafte Kost. Fisch und leicht verdauliches Eiweiß wirken unterstützend. Vermeide alles Berauschende.",
    foodFavor: ["Sanfte, nahrhafte Kost", "Fisch und leicht verdauliches Eiweiß"],
    foodAvoid: ["Berauschende Substanzen"]
  }
];
